### ISSUE TITLE
Which Plugin API should we use to compile?

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#1]
This used opencpn.lib v4.2.0  will try most current next

> "C:\Users\Rick\Documents\GitHub\testplugin_pi\build\ALL_BUILD.vcxproj" (default target) (1) ->
> "C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_pi.vcxproj" (default target) (3) ->
> (ClCompile target) ->
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(384): error C2065: 'GL_SMOOTH_LINE_WIDT
> H_RANGE' : undeclared identifier [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_pi.
> vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(393): error C2065: 'GL_ALIASED_LINE_WID
> TH_RANGE' : undeclared identifier [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_pi
> .vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(576): error C2065: 'GL_SMOOTH_LINE_WIDT
> H_RANGE' : undeclared identifier [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_pi.
> vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(585): error C2065: 'GL_ALIASED_LINE_WID
> TH_RANGE' : undeclared identifier [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_pi
> .vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(633): error C2065: 'GL_SMOOTH_LINE_WIDT
> H_RANGE' : undeclared identifier [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_pi.
> vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(642): error C2065: 'GL_ALIASED_LINE_WID
> TH_RANGE' : undeclared identifier [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_pi
> .vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(1133): error C2065: '_GLUfuncptr' : und
> eclared identifier [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_pi.vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(1133): error C2660: 'gluTessCallback' :
>  function does not take 2 arguments [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_
> pi.vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(1134): error C2065: '_GLUfuncptr' : und
> eclared identifier [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_pi.vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(1134): error C2660: 'gluTessCallback' :
>  function does not take 2 arguments [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_
> pi.vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(1135): error C2065: '_GLUfuncptr' : und
> eclared identifier [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_pi.vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(1135): error C2660: 'gluTessCallback' :
>  function does not take 2 arguments [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_
> pi.vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(1136): error C2065: '_GLUfuncptr' : und
> eclared identifier [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_pi.vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(1136): error C2660: 'gluTessCallback' :
>  function does not take 2 arguments [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_
> pi.vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(1137): error C2065: '_GLUfuncptr' : und
> eclared identifier [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_pi.vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(1137): error C2660: 'gluTessCallback' :
>  function does not take 2 arguments [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_
> pi.vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(1189): error C2065: '_GLUfuncptr' : und
> eclared identifier [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_pi.vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(1189): error C2660: 'gluTessCallback' :
>  function does not take 2 arguments [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_
> pi.vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(1190): error C2065: '_GLUfuncptr' : und
> eclared identifier [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_pi.vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(1190): error C2660: 'gluTessCallback' :
>  function does not take 2 arguments [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_
> pi.vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(1191): error C2065: '_GLUfuncptr' : und
> eclared identifier [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_pi.vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(1191): error C2660: 'gluTessCallback' :
>  function does not take 2 arguments [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_
> pi.vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(1192): error C2065: '_GLUfuncptr' : und
> eclared identifier [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_pi.vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(1192): error C2660: 'gluTessCallback' :
>  function does not take 2 arguments [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_
> pi.vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(1193): error C2065: '_GLUfuncptr' : und
> eclared identifier [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_pi.vcxproj]
>   C:\Users\Rick\Documents\GitHub\testplugin_pi\src\tpdc.cpp(1193): error C2660: 'gluTessCallback' :
>  function does not take 2 arguments [C:\Users\Rick\Documents\GitHub\testplugin_pi\build\testplugin_
> pi.vcxproj]
> 
>     13 Warning(s)
>     26 Error(s)
> 
> Time Elapsed 00:00:24.87
>

**Comment by rgleason** [comment]
Tried opencpn.lib v4.8.2 same errors.  Sorrry

**Comment by jongough** [comment]
Hi Rick,
   Added missing OpenGL includes and global variable. Windows should now compile this. Patch is now 1.0.4. I have compiled and tested it under windows 10 and, for me, it works. You will need the latest OD 1.5.17. You will also need to copy the icons from data to the appropriate place in your test installation. 

Regards
   Jon

**Comment by rgleason** [comment]
This is helpful. I thought it was to test the ocpn_draw 1.5.17 plugin!

> With the ODAPI select the type of object you want to create, click on the chart to pick the click location for its creation or provide the lat/lon, then click create. The object 'should' be created. The idea is really to debug the process to see what happens. The testplugin should 'do' what a plugin would do to create stuff, i.e. it is a working example, and it allows me to test the API without having to drive another plugin.

It works.  The first thing I did was try to create an ODAPI Object, a Boundary.  I clicked on the chart then clicked "Create" it crashed Opencpn.  Later I tried clicking on the chart in 3 places minimum then click on create. This does not seem to make a difference, but for some reason it diid not crash.  So I think it is a problem with some boundary initializtion problem.  

Anyway the objects all work, but I can't control sequential boundary points, they just get entered all at once where the program determines.

![screenshot 143](https://user-images.githubusercontent.com/2363959/40715520-d121dc00-63d3-11e8-9110-eec08d4a526c.png)

**Comment by rgleason** [comment]
Jon, I compiled your recent commit. It looks like it adds information for the user basically. No new functions to test.

**Comment by rgleason** [comment]
I think this needs to be closed.
