### ISSUE TITLE
Plotting routes using testplugin_pi and ocpn_draw_pi

### ISSUE THREAD

**Issue by Hjorth2** [jongough/testplugin_pi#101]
Hi,

I've been using the testplugin to plot some custom icons in OpenCPN. I've managed to send drawing commands via other scripts written in Python, and I think overall it has been very accessible and well made, so thank you for that. 
I'm fiddling with making a computer suggest routes based on the surroundings and my question is therefore, if it is possible to send route commands to OpenCPN using the testplugin. 
I've used the route drawing tool before, but what I'm looking for is to simply send a command from a different script, specifying the waypoints in the route and then have that be plotted with the charts. Is this doable?
Thank you.

**Comment by jongough** [comment]
This plugin only interacts with ODraw and is ment to show/test the interaction. There is no ability in ODraw to create a true 'Route' in OCPN. There is a plugin function available in OCPN, AddPlugInRoute, but to use it requires that your code is in a plugin, or you could use testplugin_pi as an example and create your own plugin to interact in the way you want.

**Comment by rgleason** [comment]
May I suggest a new plugin called Javascript by Tony Voss as a possibility?  Please look at the Dev Plugins wiki to learn more.
Tony seems to be looking for good applications for his plugin, yours may be perfect.
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:plugins:beta_plugins:javascript
We just added his page today. Write him via PM on CF he may be very interested.

**Comment by rgleason** [comment]
Perhaps it is time to close this?

**Comment by jongough** [comment]
It could be moved to ODraw where the DR tool 'could' generate a route. It should not be an issue against testplugin.

**Comment by rgleason** [comment]
Only way to move it is for you to close it and open a new issue in DR.
I cannot close this. Only OP and owner.

**Comment by jongough** [comment]
Closed as not relevant to testplugin_pi
