### ISSUE TITLE
mingw build: wrong target.

### ISSUE THREAD

**Issue by leamas** [jongough/testplugin_pi#109]
As of current code, the mingw metadata contains `<target> mingw </target>` . However, opencpn expects _mingw-x86_64_.  As a consequence, the  plugin is not available in a mingw opencpn build.

**Comment by rgleason** [comment]
Fixed https://github.com/jongough/testplugin_pi/pull/111

**Comment by rgleason** [comment]
Fixed https://github.com/jongough/testplugin_pi/pull/114

**Comment by jongough** [comment]
Fixed in master branch

**Comment by leamas** [comment]
Indeed, in 498e6cd350c544. Closing
