### ISSUE TITLE
CircleCI deployment to CloudSmith issue after clone of Jon Gough testplugin + personal changes

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#11]
Just started over using your Testplugin_pi repository, essentially cloning it and starting over.
1. Changed cmakelists.txt personal details
2. Left set(CPACK_PACKAGE_CONTACT "Jon Gough") on Lines 22 & 37 (duplicated?) untouched.
3. Made and enabled a new repository  "opencpn-plugins"  to conform with your setup.
4. Then pushed to my remote repository and appveyor succeeded and 3 files uploaded to "opencpn-plugins".
5. However all 4 of the circleci failed and did not upload to opencpn-plugins. The error is

- Checking raw package upload parameters ... ERROR
- Failed to validate upload parameters! (status: 404 - Not Found)
- Detail: Not found.
- Hint: This usually means the user/org is wrong or not visible.

6. Do I have to re-establish the Cloudsmaith_api_key in CircleCi AGAIN?  I've missed something. This is coming from the same testplugin_pi directory and the same cmake_flatpak_test branch.

**Comment by rgleason** [comment]
This does download:
https://dl.cloudsmith.io/public/rick-gleason/opencpn-plugins/raw/names/testplugin-msvc-10.0.14393-installer/versions/1.0.41.+40.e610c30/testplugin_pi-1.0.41.0-ov50-1.16-pi-msvc-win32.exe

This does not seem to be uploading, but it has the same configuration:
https://dl.cloudsmith.io/public/rick-gleason/opencpn-plugins/raw/names/testplugin-flatpak-18.08.gz/versions/v1.0.41.7/testplugin_pi-1.0.41.7-ov50-1.16_flatpak-18.08.tar.gz

So the problem must be something related to user/org
Hint: This usually means the user/org is wrong or not visible.
Is there a key missing again? 
In CircleCI Environment Variables I  have removed and redone the Cloudsmith_API_Key
Perhaps this is about CircleCI access to Github?

```
  <tarball-url>
    https://dl.cloudsmith.io/public/rick-gleason/opencpn-plugins/raw/names/testplugin-flatpak-18.08.gz/versions/v1.0.41.7/testplugin_pi-1.0.41.7-ov50-1.16_flatpak-18.08.tar.gz
  </tarball-url>
  <info-url> https://opencpn.org/OpenCPN/plugins/ocpn_draw.html </info-url>
</opencpn-plugin>
+ cloudsmith push raw --republish --no-wait-for-sync --name testplugin-flatpak-18.08-metadata --version v1.0.41.7 --summary 'testplugin opencpn plugin metadata for automatic installation' rick-gleason/testplugin_pi-stable /home/circleci/project/build/testplugin-plugin-flatpak-18.08.xml
Checking raw package upload parameters ... -ERROR
Failed to validate upload parameters! (status: 404 - Not Found)
```

**Comment by jongough** [comment]
I have just checked your latest build and the cloudsmith repository you are trying to use is:
rick-gleason/testplugin_pi-stable
but this does not exist, as far as I can see.

**Comment by rgleason** [comment]
Ok so can you suggest where I change that to "opencpn-plugins..."??
After having started over, basically cloned your repository again, and then setup personal changes, I now find that the appveyor is deploying and acting as expected, but all of the circleci builds are failing.  I have reinstalled the cloudsmith_api_key in my circleci    testplugin_pi  and checked all the repository settings but am I missing something or is there something I need to change in testplugin cmake?

https://github.com/rgleason/testplugin_pi/commits/cmake_flatpak_test

https://github.com/rgleason/testplugin_pi/runs/331542773

Have I missed something in the setup?

**Comment by jongough** [comment]
I changed CMakeLists.txt to allow changes to the cloudsmith repository to be used. The following is the current code:
```
set(PARENT "opencpn")
set(PACKAGE "testplugin")
set(VERBOSE_NAME "Testplugin")
set(CPACK_PACKAGE_CONTACT "Jon Gough")
set(GIT_USER "jongough")
set(GIT_REPOSITORY_NAME "testplugin_pi")
message(STATUS "CIRCLECI: ${CIRCLECLI}, Env CIRCLECI: $ENV{CIRCLECI}")
if($ENV{CIRCLECI})
  set(GIT_REPOSITORY_HOST "github.com")
  set(GIT_REPOSITORY_DIR "${GIT_USER}/")
#  set(GIT_REPOSITORY_BRANCH "master")
  set(GIT_REPOSITORY_BRANCH "cmake_flatpak_test")
else()
  set(GIT_REPOSITORY_HOST "git.eclipse.com.au")
  set(GIT_REPOSITORY_DIR "")
  set(GIT_REPOSITORY_BRANCH "cmake_flatpak_test")
endif()
set(CLOUDSMITH_USER "jon-gough")
set(CLOUDSMITH_BASE_REPOSITORY "${GIT_REPOSITORY_NAME}")
```
Notice the last statement which lets you set the cloudsmith repository name without the extensions -pkg', '-manual', etc. The default is to use the git repository name, but just change this to what you want.

**Comment by rgleason** [comment]
Ok, that's good, but the actual problem is in  circleci-upload.sh.in 

Lines 17- 20 which I've commented out
# STABLE_REPO=${CLOUDSMITH_STABLE_REPO:-'@CLOUDSMITH_USER@/@GIT_REPOSITORY_NAME@-stable'}
# UNSTABLE_REPO=${CLOUDSMITH_UNSTABLE_REPO:-'@CLOUDSMITH_USER@/@PACKAGE@'}
# STABLE_PKG_REPO=${CLOUDSMITH_PKG_REPO:-'@CLOUDSMITH_USER@/manual'}
# PKG_EXT=${CLOUDSMITH_PKG_EXT:-'deb'}

and added

STABLE_REPO='@CLOUDSMITH_USER@/@CLOUDSMITH_BASE_REPOSITORY@-stable'
UNSTABLE_REPO='@CLOUDSMITH_USER@/@CLOUDSMITH_BASE_REPOSITORY@'
STABLE_PKG_REPO='@CLOUDSMITH_USER@/@CLOUDSMITH_BASE_REPOSITORY@-pkg'

Is this going to be OK now, do you think?



STABLE_REPO='@CLOUDSMITH_USER@/@CLOUDSMITH_BASE_REPOSITORY@-stable'
UNSTABLE_REPO='@CLOUDSMITH_USER@/@CLOUDSMITH_BASE_REPOSITORY@'
STABLE_PKG_REPO='@CLOUDSMITH_USER@/@CLOUDSMITH_BASE_REPOSITORY@-pkg'

**Comment by rgleason** [comment]
Well now it seems to be showing the right CS repositories
```
+ STABLE_REPO=rick-gleason/opencpn-plugins-stable
+ UNSTABLE_REPO=rick-gleason/opencpn-plugins
+ STABLE_PKG_REPO=rick-gleason/opencpn-plugins-pkg
```
but it still fails

```
++ OCPN_API_VERSION=
+ tarball_name=testplugin-mingw-10.gz
++ ls '/root/project/build/*.'
ls: cannot access '/root/project/build/*.': No such file or directory
+ pkg
```

**Comment by rgleason** [comment]
CMakeLists.txt  is now

```
set(PARENT "opencpn")
set(PACKAGE "testplugin")
set(VERBOSE_NAME "Testplugin")
set(CPACK_PACKAGE_CONTACT "Jon Gough")
set(GIT_USER "rgleason")
set(GIT_REPOSITORY_NAME "testplugin_pi")
message(STATUS "CIRCLECI: ${CIRCLECLI}, Env CIRCLECI: $ENV{CIRCLECI}")
if($ENV{CIRCLECI})
  set(GIT_REPOSITORY_HOST "github.com")
  set(GIT_REPOSITORY_DIR "${GIT_USER}/")
#  set(GIT_REPOSITORY_BRANCH "master")
  set(GIT_REPOSITORY_BRANCH "cmake_flatpak_test")
else()
  set(GIT_REPOSITORY_HOST "git.eclipse.com.au")
  set(GIT_REPOSITORY_DIR "")
  set(GIT_REPOSITORY_BRANCH "cmake_flatpak_test")
endif()
set(CLOUDSMITH_USER "rick-gleason")
#set(CLOUDSMITH_BASE_REPOSITORY "${GIT_REPOSITORY_NAME}")
set(CLOUDSMITH_BASE_REPOSITORY "opencpn-plugins")
set(XML_INFO_URL "https://opencpn.org/OpenCPN/plugins/ocpn_draw.html")
set(XML_SUMMARY "Test of ODraw ODAPI and JSON interfaces")
set(XML_DESCRIPTION "Test ODraw API and demo use from another plugin")
set(APPVEYOR_TEST_DEPLOY_TO_CLOUDSMITH "true")


```

**Comment by rgleason** [comment]
mingw  your version output
```
++ VERSION=1.0.41.
++ VERSION_DATE='2019-12-03 16:12:02 +1100'
++ PKG_TARGET=mingw
++ PKG_TARGET_VERSION=10
++ VERSION=1.0.41.
++ VERSION_DATE='2019-12-03 16:12:02 +1100'
++ PKG_TARGET=mingw
++ PKG_TARGET_VERSION=10
++ OCPN_API_VERSION=
+ '[' -n '' ']'
+ VERSION=1.0.41.0+299.d3a57f9
+ REPO=jon-gough/testplugin
+ PKG_REPO=jon-gough/testplugin

```
My version now
```
+ source /root/project/build/pkg_version.sh
++ VERSION=1.0.41.
++ VERSION_DATE='2019-12-03 16:58:13 -0500'
++ PKG_TARGET=mingw
++ PKG_TARGET_VERSION=10
++ VERSION=1.0.41.
++ VERSION_DATE='2019-12-03 16:58:13 -0500'
++ PKG_TARGET=mingw
++ PKG_TARGET_VERSION=10
++ OCPN_API_VERSION=
(Starts to go astray here, something to do with the version number I think)
+ tarball_name=testplugin-mingw-10.gz
++ ls '/root/project/build/*.'
ls: cannot access '/root/project/build/*.': No such file or directory
+ pkg=
Exited with code exit status 2
```

**Comment by rgleason** [comment]
I've tried it again and they are all failing now except Appveyor whiich works properly.
They all fail with things like this:
```
++ OCPN_API_VERSION=
+ tarball_name=testplugin-darwin-10.13.6.gz
++ ls '/Users/distiller/project/build/*.'
ls: /Users/distiller/project/build/*.: No such file or directory
+ pkg=

```

**Comment by jongough** [comment]
I have just put up a patch to fix the cloudsmith_base_repository which I missed in the upload script.

**Comment by rgleason** [comment]
I've made all your changes and it is working well now.  Thanks.
https://github.com/rgleason/testplugin_pi/commits/cmake_flatpak_test

**Comment by rgleason** [comment]
Closing

**Comment by rgleason** [comment]
Changed the version to v1.0.41.8 and push with tag so that it would push to my Cloudsmith repositories   opencpn-plugins-stable and opencpn-plugins-pkg
The path does not seem to be correct.

https://app.circleci.com/jobs/github/rgleason/testplugin_pi/130

```
Throttling (rate limited) for: 0.21335360560066255 seconds ... 
+ cloudsmith push raw --republish --no-wait-for-sync --name testplugin-ubuntu-16.04.deb --version v1.0.41.8 --summary 'testplugin .deb installation package' rick-gleason/opencpn-plugins-pkgl /home/circleci/project/build/opencpn-plugin-testplugin-1.0.41.8-ov50-1.16_ubuntu-16.04.deb
Checking raw package upload parameters ... -ERROR
Failed to validate upload parameters! (status: 404 - Not Found)
Detail: Not found.
Hint: This usually means the user/org is wrong or not visible.
```

**Comment by jongough** [comment]
Sorry, fixed appveyor but not circleci. Just put up a patch to hopefully make it work.

**Comment by rgleason** [comment]
Thanks. Unfortunately there's a failure.

```
</tarball-url>
<info-url> https://opencpn.org/OpenCPN/plugins/ocpn_draw.html </info-url>
</opencpn-plugin>
+ cloudsmith push raw --republish --no-wait-for-sync --name testplugin-msvc-10.0.14393-metadata --version v.0.1.1004 v.0.1.1006 --summary 'testplugin opencpn plugin metadata for automatic installation' jon-gough/testplugin_pi-stable ./testplugin-plugin-msvc-10.0.14393.xml
Usage: cloudsmith push raw [OPTIONS] OWNER/REPO PACKAGE_FILE
Error: Invalid value for "OWNER/REPO": Must be in the form of OWNER/REPO
Command exited with code 2
```

**Comment by jongough** [comment]
I am trying to delete one of my cloudsmith repositories as I think there is an issue with a name and slug mismatch. I also get different results each time I submit the same job in appveyor. I have had download failures, upload failures, script failures all without changing anything in the code, just resubmitting the job.

**Comment by rgleason** [comment]
I'll give the changes a try, perhaps that will tell us something.

**Comment by rgleason** [comment]
Jon, the failure was due to failure to download from sourceforge.

```
rm -rf build && mkdir build && cd build
Start-FileDownload https://downloads.sourceforge.net/project/opencpnplugins/opencpn_lib/4.99.1405-vc141_xp/opencpn.lib
Start-FileDownloadInternal : Error downloading remote file: One or more errors occurred.
Inner Exception: Unable to connect to the remote server
At C:\Program Files\AppVeyor\BuildAgent\Modules\build-worker-api\build-worker-api.psm1:242 char:2
+     Start-FileDownloadInternal -Url $Url -FileName $FileName -Timeout ...
    + CategoryInfo          : NotSpecified: (:) [Start-FileDownloadInternal], Exception
```

Maybe try to re-run the build.

**Comment by rgleason** [comment]
Jon, It took two tries, but they all work now. CircleCI is pretty darn good.
https://github.com/rgleason/testplugin_pi/commits/cmake_flatpak_test

Yours, will work.   I am sure.  
Closing this.

**Comment by jongough** [comment]
See what I mean about the process not being repeatable, i.e. you may have to go through the same process multiple times to get it to work. This may cause issues for delivery when circleci jobs need to be run multiple times.

**Comment by rgleason** [comment]
Yes, agreed.  It does take about 7 minutes to complete here. In some ways its nice that it is being done in the cloud, and CircleCI is pretty convenient, allowing you to re-run it quite easily,  but I agree that sometimes you don't know if it was programming or a failed download of a file. Fortunately circleci error messages are pretty good, but I don't know them that well.

PI Dev will have to check the builds [inconvenient] until they finish properly and then test anyway.
