### ISSUE TITLE
Unstripped mingw plugins way too big.

### ISSUE THREAD

**Issue by leamas** [jongough/testplugin_pi#110]
The mingw plugin is not stripped and too big. See: https://github.com/OpenCPN/OpenCPN/issues/2065

**Comment by rgleason** [comment]
Jon , look in cmake/plugininstall.cmake starting at line 15 for code that needs to be adopted and modified.

**Comment by jongough** [comment]
Why create the symbols and  then strip then. Is there a way to no create them in the first place?

**Comment by jongough** [comment]
Made a change to exclude all symbols from linked module. The size is much smaller now.

**Comment by leamas** [comment]
I see the change in 82280ecd3 (and some previous ones).

The debug info is generated by the -g compiler flag, dropping this means dropping the debug info.

The reason for the workflow to first generate the debugging symbols and then stripping them is the legacy, native linux plugins. In a traditional, standard linux toolchain the program is built with debugging symbols. The toolchain then strips the symbols after creating a debug package where they live. Users installs the debug package when debugging the program.

The cmake way is the build profiles. A clean, proper fix would be to leave the -g flag in place for debug builds, dropping it for release builds. This is the standard cmake setup, so just leaving the flags in their default state should fix it (possibly adding some -W flags without replacing the original values). In such a scenario, building a release package would solve the basic problem while leaving a clean option for devs to build it with debug symbols (and related -O0 flags etc.)

**Comment by jongough** [comment]
I used the -Wl,--exclude-all-symbols linker option. This is supposed to only suppress symbols which are not explicitly exported, hence it should work for what is needed.
Depending on the 'target' the build type is changed. For 'prod' it is partially optimised, for 'beta' and 'alpha' the debugging information is generated. All three versions are available, when generated, so if debugging is required the 'non-prod' version would be installed and run.

**Comment by leamas** [comment]
> This is supposed to only suppress symbols which are not explicitly exported, hence it should work for what is needed.

Did some simple checking with the shipdriver plugin. Results:

  - Not stripped, no extra flags: 11277928
  - Stripped: 711056
  - With Wl,--exclude-all-symbols: 11277928

i. e., the flag makes no difference for the size. I might have got it wrong, for sure, doing this in a haste. However, when I read the docs for --exclude-all-symbols I understand it as excluding symbols from the list of exported ones rather than excluding them from the object file.

**Comment by leamas** [comment]
hm... Eventually, this is about the plugin in the master catalog. As long as this is stripped everything is fine.

When I look into https://cloudsmith.io/~opencpn/repos/testplugin-prod/ the library looks OK, it's size is rougly the same as other plugins, and is reported as stripped.

However, in the master catalog, currently at f1f7f3a,  the link seems broken:

```
$ git rev-parse HEAD
f1f7f3ab673eecd61d40dab8efc09049fb5013ca
$  wget $(grep testplugin_pi-1.0.139.0-mingw ocpn-plugins.xml)
--2020-11-19 12:44:23--  https://dl.cloudsmith.io/public/opencpn/testplugin-beta/raw/names/testplugin_pi-1.0.139.0-mingw-x86_64-x86_64-10-mingw-tarball/versions/1.0.139.0+2091.fbd98b6/testplugin_pi-1.0.139.0-mingw-x86_64-x86_64-10-mingw.tar.gz
Resolving dl.cloudsmith.io (dl.cloudsmith.io)... 13.33.243.70, 13.33.243.45, 13.33.243.60, ...
Connecting to dl.cloudsmith.io (dl.cloudsmith.io)|13.33.243.70|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-11-19 12:44:24 ERROR 404: Not Found.
```

Obviously , this is unrelated to the basic issue here. However, ít makes it hard to verify that everything actually is ok and the bug can be closed.

**Comment by rgleason** [comment]
`0-11-19 12:44:23--  https://dl.cloudsmith.io/public/opencpn/testplugin-beta/raw/names/testplugin_pi-1.0.139.0-mingw-x86_64-x86_64-10-mingw-tarball/versions/1.0.139.0+2091.fbd98b6/testplugin_pi-1.0.139.0-mingw-x86_64-x86_64-10-mingw.tar.gz`

This is from my PR while Jon was away, and I had not resolved the symbol removal issue at that point, but had fixed the mingw target

**Comment by rgleason** [comment]
I think this is done and can be closed..

**Comment by leamas** [comment]
Last I checked, I couldn't verify the status from the master catalog. Furthermore, the linker flag introduced by  82280ec doesn't work ans should perhaps be dropped (no purpose if the published tarball is stripped, besides being useless).

leaving bug open

**Comment by jongough** [comment]
The compiler is supposed to honour that flag and it is supposed to exclude symbols. It did not seem to be as effective as it should have been. The same can be said for the '-s' flag. It works in all environments except mingw. As a work around I put in the strip process. 

The build process outputs the following to show that stripping has worked:
```
 Running post build action on .
ls -la libtestplugin_pi.dll
-rwxr-xr-x 1 root root 21043512 Nov 24 07:03 libtestplugin_pi.dll
sh -c 'strip libtestplugin_pi.dll'
ls -la libtestplugin_pi.dll
-rwxr-xr-x 1 root root 992256 Nov 24 07:03 libtestplugin_pi.dll
```
Notice the size difference

**Comment by leamas** [comment]
Yes, that looks sound. The size is also roughly the same as other plugins.

**Comment by leamas** [comment]
As for the exclude-all-symbols, _man ld_ tells us

    --exclude-all-symbols
           Specifies no symbols should be automatically exported.  [This option is specific to the i386 PE targeted port of the linker]

To me, this seems like it should not have any impact on the size. I doesn't  talk about removing code, just that the symbols shouldn't be exported. So, things are like they are supposed to be I guess (no impact on size).

**Comment by leamas** [comment]
After a night's sleep: issue reported is fixed in bce331f9.

Note that the same commit adds the useless and potentially dangerous -Wl,--exclude-all-symbols linker flag. The assumption that a symbol which isn't  exported is or should be excluded from the library is plain wrong. The question if a symbol is exported or not is just about the symbol table, probably just a bit flipped for each symbol. Tools like nm(1) and readelf(1) can be used to check symbols and their status, including if the export flag is set.  

However, the linker flag issue is a different thing, more or less unrelated to reported bug. Closing

**Comment by jongough** [comment]
Reading these articles it would appear that -Wl,--exclude-all-symbols is not 'useless and potentially dangerous':
[https://stackoverflow.com/questions/2810118/how-to-tell-the-mingw-linker-not-to-export-all-symbols#21902439](https://stackoverflow.com/questions/2810118/how-to-tell-the-mingw-linker-not-to-export-all-symbols#21902439)
[http://anadoxin.org/blog/control-over-symbol-exports-in-mingw-linker.html](http://anadoxin.org/blog/control-over-symbol-exports-in-mingw-linker.html)
[https://sourceware.org/binutils/docs/ld/WIN32.html](https://sourceware.org/binutils/docs/ld/WIN32.html)
__declspec(dllexport) is used in OCPN and specifically for the definition of the plugin via opencpn_plugin *create_pi and destroy_pi. This should have forced off the --export-all-symbols automatic behaviour, but....

This appears to be a continuing issue with mingw.

**Comment by leamas** [comment]
Indeed, but another issue.  The code related to the symbols is not removed in any case.

Note that your links is about not exporting symbols from a statically linked libraries. This is entirely  different from stripping debug info. its about excluding symbols from the exported section in the symbol table. 

Again:  that  a symbol isn't exported doesn't mean the corresponding code is excluded from the dynamic library. It just means that other libs cannot link to it i. e., it's just used internally in the library.

**Comment by jongough** [comment]
The "-Wl,--strip-all" option seems to do exactly what the strip command does. For a slightly reduced action "-Wl,--strip-debug" removes the debug information only. With the --strip-all option there is no need to run the strip command as the files are the same size.
[https://www.systutorials.com/docs/linux/man/1-i686-w64-mingw32-ld/](https://www.systutorials.com/docs/linux/man/1-i686-w64-mingw32-ld/)

**Comment by leamas** [comment]
Seems fine, should solve it.
