### ISSUE TITLE
flatpak metadata: wrong <target>

### ISSUE THREAD

**Issue by leamas** [jongough/testplugin_pi#112]
The flatpak metadata contains `<target>flatpak</flatpak>`, should be `<target>flatpak-x86_64</flatpak>`. Effectively, this makes the plugin hidden and un-installable. See https://github.com/OpenCPN/OpenCPN/issues/2095

**Comment by jongough** [comment]
Should be fixed by 1.0.140.3 .

**Comment by leamas** [comment]
Yes, in f93dd1681b2737. Closing
