### ISSUE TITLE
CI-settings.cmake

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#13]
Jon, I've been thinking about your observation that some of the personalized CI Settings that you've placed very conveniently at the head of CMakeLists.txt, affects the ability to make pull requests without changing them. 

I do not know if this is possible, but if these variables could be put in a file under the Cmake directory (perhaps) and the file added to the gitignore, we would not have this trouble with a PR.

**CI-settings.cmake**
set(GIT_USER "rgleason")
set(GIT_REPOSITORY_BRANCH "cmake_flatpak_test")
set(CLOUDSMITH_USER "rick-gleason")
#set(CLOUDSMITH_BASE_REPOSITORY "${GIT_REPOSITORY_NAME}")
set(CLOUDSMITH_BASE_REPOSITORY "opencpn-plugins")

**Comment by jongough** [comment]
I don't think the PR process will be affected too badly unless the person needs to test the installation process. I can make a change to externalise some of these settings but they cannot be in a gitignore as they are needed for the circleci, appveyor and travis builds. These builds do a get from the git repository and then run the cmake process. So all the information needs to be available for them.

I think that once the new process is working then the developer will be using their own git clone and working with cloudsmith and installing their own generated versions. Once this is sorted then they will need to restore the values for the real repository.

The closest I could get to something like this you can see in CMakeLists.txt where I check if the process is running under circleci and change where git is for that test. I think I will have to remove it shortly as it is likely to cause issues.

At the moment testing the process is very difficult as the xml file stuff does not seem to be particularly robust and makes it difficult to run tests with different versions from different locations.

**Comment by rgleason** [comment]
> ".. all the information needs to be available for them."
> "..developer using their own git clone, cloudsmith, installing own generated versions.."
> '..then they will need to restore the values for the real repository"
> 
OK, Then we should all do this in the CMakeLists.txt

```
# CI-settings.cmake  jongough
set(GIT_USER "jongough")
set(GIT_REPOSITORY_BRANCH "cmake_flatpak_test")
set(CLOUDSMITH_USER "jon-gough")
set(CLOUDSMITH_BASE_REPOSITORY "${GIT_REPOSITORY_NAME}")
# set(CLOUDSMITH_BASE_REPOSITORY "testplugin_pi")

# CI-settings.cmake
#set(GIT_USER "rgleason")
#set(GIT_REPOSITORY_BRANCH "cmake_flatpak_test")
#set(CLOUDSMITH_USER "rick-gleason")
#set(CLOUDSMITH_BASE_REPOSITORY "${GIT_REPOSITORY_NAME}")
#set(CLOUDSMITH_BASE_REPOSITORY "opencpn-plugins")
```

We would then just have to comment out and in the appropriate lines when making a PR back to the parent repository.

**Comment by rgleason** [comment]
Any other thoughts?  After that I'll close this.

**Comment by jongough** [comment]
I am thinking about it. Perhaps this should be raised in Alec's PR as an issue?

**Comment by rgleason** [comment]
I think this should be closed now.

**Comment by jongough** [comment]
It may be best as changing cmake files after deployment by the developer is asking for trouble. I think this is why it may be best to have an OCPN cloudsmith repository that all developers can deploy to (or their git with tag uploads/accepts) with individual repository areas. But.....

Alec should be part of the process for making these decisions, the process is his after all. All I am doing is trying to make it usable.
