### ISSUE TITLE
CMakeLists..txt  version number needed.

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#14]
I believe we should implement a Version system

"CI-CMake Version Number: 1.0.0"
Change Notes:  [Additional notes detailing particular changes made differing from the Version]

To ease understanding what CI-CMake is being used by a given plugin.
The number will enable easier updates of the CI-CMake system.

**Comment by jongough** [comment]
Very good idea. It also needs changes to the OCPN API as I think versioning may be needed to find the 'shared' data and possibly the 'private' data. When I get a version of this process working I will be testing the versioning capability as at the moment the searches for these items occur in a sequence and the first file that fits is provided irrespective of whether it is the correct one.

**Comment by rgleason** [comment]
Can you put a CI CmakeList number on it yet?
