### ISSUE TITLE
Alpha channel is not deploying properly v1..0.161 and  v1.0.162

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#144]
From a non-master branch, config.yml  deployment=true
https://github.com/rgleason/LogbookKonni_pi/tree/master-updateFE
No files deployed!!!
https://cloudsmith.io/~opencpn/repos/logbookkonni-alpha/packages/

**Comment by rgleason** [comment]
https://github.com/rgleason/LogbookKonni_pi/issues/15

**Comment by rgleason** [comment]
Testplugin, turned on deploy and pushed. Did not deploy.  Have left a message with CS to see if any policies have changed.

**Comment by rgleason** [comment]
Jon, I added control and it made no difference. The plugins are not deploying!

https://app.circleci.com/pipelines/github/rgleason/LogbookKonni_pi/49/workflows/21fd0265-ffc9-4122-b30b-958e1d2e3772/jobs/492

https://cloudsmith.io/~opencpn/repos/logbookkonni-beta/packages/
https://cloudsmith.io/~opencpn/repos/logbookkonni-alpha/packages/

Same issue applies to Testplugin.

Going to try Watchdog now.

**Comment by rgleason** [comment]
Committed to Watchdog with deploy=true
https://cloudsmith.io/~opencpn/repos/watchdog-beta/packages/

https://cloudsmith.io/~opencpn/repos/watchdog-beta/packages/
And v2.4.30.3 is deploying!!!

This indicates to me that it is a problem with Testplugin, not Cloudsmith, certificates, or anything else.

**Comment by jongough** [comment]
I have just pushed a new version of cloudsmith-upload-sh.in that should fix that issue. The change was introduced to allow local build deploys to cloudsmith as well as deploys to a local directory (makes testing faster), but there was an error in the logic so the deploy did not happen. The push should have fixed that.

**Comment by jongough** [comment]
I have just pushed testplugin 1.0.163 with the latest changes and it seems to be deploying OK. I will merge it with the master when the pull builds have finished.

**Comment by rgleason** [comment]
Fixed, Thanks.
https://cloudsmith.io/~opencpn/repos/logbookkonni-alpha/packages/
