### ISSUE TITLE
Make it again possible to build the plugin inside OpenCPN source tree #38 

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#148]
Is this change appropriate to testplugin_in

Make it again possible to build the plugin inside OpenCPN source tree
#38 

https://github.com/delatbabel/LogbookKonni-1.2/pull/38/commits/1b370680d9a002573cbe86d1438a70568d72a34c

**Comment by jongough** [comment]
I am not sure what this change is supposed to be achieving. Is there any explanation as to why it was needed?

**Comment by rgleason** [comment]
Well, here is the discussion,  Pavel doesn't really get the development of plugins and really does not care, as he says abruptly. He never listens to me anyway.

https://github.com/delatbabel/LogbookKonni-1.2/pull/38

**Comment by rgleason** [comment]
I think I can close now
