### ISSUE TITLE
Broken download urls

### ISSUE THREAD

**Issue by leamas** [jongough/testplugin_pi#156]
There seem to multiple broken download urls in current master catalog for testplugin. See https://github.com/OpenCPN/OpenCPN/issues/2315

**Comment by jongough** [comment]
This is a testplugin and is not for general consumption. It is quite likely that it will have broken links, a quite valid test for installation. I will create a new version and put it into master then update the catalog. It may take a day or so.

**Comment by leamas** [comment]
> This is a testplugin and is not for general consumption.

Still, it's in the catalog, in the master banch. If it's indeed not meant to be used by regular users, it might perhaps make sense to add this fact to the description? Or perhaps just drop it from master, using Beta branch for testing? Just my 5 öre...

**Comment by rgleason** [comment]
Thanks Alec. I am sure Jon and I can get these fixed, but it will be several days. As far as the plugin actually working, we won't know as there are few reports about that.

**Comment by jongough** [comment]
Master catalog has been updated with latest 2 releases.
