### ISSUE TITLE
Drop testplugin, Android, due to installation error, tarball layout e… 

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#164]
https://github.com/OpenCPN/plugins/commit/f1b13ae5d1b569edff1ccde8bf6b28950a3e5898

**Comment by jongough** [comment]
What is the problem? As far as I know it works OK.

**Comment by rgleason** [comment]
You know as much as I do. See the link. It has been removed anyway.

Perhaps ask bsbcat. They have new checks i believe.
