### ISSUE TITLE
Formatting of Plugins?

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#169]
This seems to be happening to the internal plugins

https://github.com/OpenCPN/OpenCPN/pull/2410

https://github.com/OpenCPN/OpenCPN/pull/2408/files/8658c5ae185f857287ec52462268140eb7e18842..2d6c9571ded0d2a311c60499ec837d8173cbfc6e

https://github.com/OpenCPN/OpenCPN/pull/2406

**Comment by jongough** [comment]
Testplugin does not use udev. The only references are in the OCPN supplied android master.zip file. So this does not affect testplugin..
