### ISSUE TITLE
State of Testplugin 

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#170]
How is the state, is it going to change a lot in near future?
Have you got it pretty much up to current builds?

I might have some time to start over in Sean's

**Comment by jongough** [comment]
I have just added the darwin-wx315 build and am in the process of pushing it through. This is the only change currently in progress.

**Comment by jongough** [comment]
V1.0.175.3 contains the latest fixes and is in the plugins-prod and beta downloads. There are no more changes planned, just fixes for errors and keeping up to date with the latest changes to plugin handling, as always.

**Comment by rgleason** [comment]
Thanks, Jon, will start up again.
