### ISSUE TITLE
wxfax is updated to 1.0.175.3 and working ok

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#174]
I won't push this up yet Jon, so you can finish your work, but it is nice to know that it updated so easily.
When you think you are pretty much current  (until the next round of changes) let me know please.
Thanks so much.

**Comment by rgleason** [comment]
Or do you want me to add the most recent changes and then push it up to circleci to see what finishes building?

**Comment by jongough** [comment]
I have just put up 1.0.175.4 which contains the fix for the flatpak download. I am just making it into a prod version so that it will be in the opencpn/plugins-prod.

**Comment by rgleason** [comment]
Thanks Jon.  Wxfax is push up with those updates just now.
