### ISSUE TITLE
LIBHDRS  

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#176]
It does not look to me like set LIBHDRS is being used.
the  libs/wx   don't exist and target  does not list it.

```
set(LIBHDRS
    libs/GL/gl.h
    libs/GL/gl_private.h
    libs/GL/glext.h
    libs/GL/glu.h
    libs/wx/include/json_defs.h
    libs/wx/include/jsonreader.h
    libs/wx/include/jsonval.h
    libs/wx/include/jsonwriter.h)
```

**Comment by jongough** [comment]
LIBHDRS is not used but the contents are used via include_directories lines 221 & 223 in. The LIBHDRS is a reminder that they are actually used in the project. The LIBSRC is used in line 231.

**Comment by rgleason** [comment]
Ok, I understand, but still dont know how I should use this. Also the wx files dont exist in testplugin. So i would think that we would get ereors.

**Comment by jongough** [comment]
Remember, this exists in the 'plugins customisable' section, i.e. it is up to the plugin developer/owner/maintainer to set what they want here. In this case I have created this and used it in the past to build the plugins, but now I use them as reminders of what I need to have available. A plugin using Frontend2  does not have to have this at all. There are two that you need to have to enable localization to work, SRCS & HDRS.

**Comment by rgleason** [comment]
Thanks that will help.  Just got Polar_pi working but I  am having trouble with svg icons working for some reason, so I have walked it back for the time being.

**Comment by jongough** [comment]
Nothing should have changed in that area of frontend2. If you are not getting the icons make sure they are being packaged, i.e. they are in the 'data' directory or the 'UserIcons' directory.

**Comment by rgleason** [comment]
Summary
To build locally you must use SRCS & HDRS.
These items below do not have to be used but are reminders of what might be needed. 
LIBHDRS is not used but the contents are used via include_directories lines 221 & 223 in. 
LIBHDRS is a reminder that they are actually used in the project. 
LIBSRC is used in line 231.

**Comment by jongough** [comment]
Again, only SRCS and HDRS are needed. They are used in other PluginLocalization.cmake for pot files. The others I use to help me with consistency and knowing what is needed and not needed to build the project. Much has now moved to the 'libs' directory and these are now subordinate builds to the main package so there is less need for having files other than project files in the main CMakeLists.txt.

You will note that I have OCPNSRC & OCPNHDRS as list names. I use these ones to indicate which files are taken from OCPN and 'may' need updating when OCPN changes. Any file I take from OCPN and modify will have a new filename, usually the existing filename with OD put on the front. At this point it is moved to the SRCS or HDRS lists. Again, this helps me keep track of stuff over time.

Frontend2 should make very few hard requirements for names, hence only the two being used, and then only for localisation. The rest is up to the individual plugin developer. Testplugin_pi is an example of the use of frontend2 and is in the form I would expect a developer to use as a skeleton for building their own plugin. The idea being to hide all the autobuild complexity and leave the developer to worry about building a runable plugin on whatever platform they want to use. When they are ready to share the plugin they just put it up on github and the associated actions will build the current set of installables. There are continuing issues with the build as OCPN, Plugin Manager and the supported platforms keep on changing which I try to keep abreast of.

**Comment by rgleason** [comment]
OCPNSRC & OCPNHDRS used as as list names.
I am updating plots_pi now.    set(OCPNHDRS  has 3 new files.  Are they necessary for Plots?

set(OCPNHDRS
    ocpninclude/cutil.h   <--- This one
    ocpninclude/ocpn_plugin.h
    ocpninclude/pluginmanager.h
    ocpninclude/shaders.h  <--- This one
    ocpninclude/TexFont.h
    ocpninclude/vector2D.h  <--- This one
    libs/ocpn-api/ocpn_plugin.h

**Comment by rgleason** [comment]
Plots seems to build without those files.

**Comment by rgleason** [comment]
Plots is still building, but flatpak failed with same issue as Polars
I am not configuring something right.

```
/var/lib/flatpak/exports/share'
'/home/circleci/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.
error: Can't load uri https://flathub.org/repo/flathub.flatpakrepo: Unacceptable TLS certificate
Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by jongough** [comment]
The build for flatpaks should be fixed with 1.0.176.0.

**Comment by jongough** [comment]
The XDG_DATA_DIRS is part of ocpn_plugin.h and was introduced with API 1.16, see line 1282 in the header file. As far as I know this all works for testplugin and OD, so it should work for weather_routing and plots.

**Comment by jongough** [comment]
Looking at plots_pi the use of 'SRC_PLOTS' and 'HDR_PLOTS' may not work with localisation. These are by default 'SRCS' & 'HDRS'.

**Comment by rgleason** [comment]
Plots builds locally as it is, would this be a problem in the circleci environment?

**Comment by jongough** [comment]
The build will be OK it just will not build the POT, PO files needed for multi-language support.

**Comment by rgleason** [comment]
Got it. So I should keep the SRCS and HDRS  format.

**Comment by jongough** [comment]
I know it is a change, but if you can it will allow the whole process to work, including on the remote builds. To allow extra names would increase the complexity of the main cmake file and I am not sure it would be understandable when done.

**Comment by rgleason** [comment]
Jon, you are telling me I have to reorganize about 20 plugins with the news of this change. I can certainly do it but there are always headaches and glitches getting it all to work when these kinds of changes occur. Also I am about halfway through all the plugiins now and I just found out about this.
