### ISSUE TITLE
PIM Download Script  not working 

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#205]
Why don't these work?  Nothing ever stays the same around here.
I guess not.  Yes, there appears to be a new script that is trying to delete files rather than letting me do it.

https://cloudsmith.io/~opencpn/repos/celestial-navigation-prod/packages/

fcgle@Hesper MINGW64 ~/source/plugins (master)
$ ./download_xml_bash.sh celestial-navigation 2.4.36.0 opencpn prod
Issuing command: wget -q -O - https://cloudsmith.io/~opencpn/repos/celestial-navigation-prod/packages/?q=*2.4.36.0*.xml
Show current files that match criteria
ls: cannot access 'metadata/celestial-navigation*-2.4.36.0*xml': No such file or directory
Deleting current files that match criteria
rm: cannot remove 'metadata/celestial-navigation*-2.4.36.0*xml': No such file or directory
Finding files on remote cloudsmith repository
./download_xml_bash.sh: line 38: wget: command not found
Downloading files found that match criteria
Files downloaded
ls: cannot access 'metadata/celestial-navigation*-2.4.36.0*xml': No such file or directory

========================

https://cloudsmith.io/~opencpn/repos/watchdog-prod/packages/

fcgle@Hesper MINGW64 ~/source/plugins (master)
$ ./download_xml_bash.sh watchdog 2.4.36.0 opencpn prod
Issuing command: wget -q -O - https://cloudsmith.io/~opencpn/repos/watchdog-prod/packages/?q=*2.4.36.0*.xml
Show current files that match criteria
ls: cannot access 'metadata/watchdog*-2.4.36.0*xml': No such file or directory
Deleting current files that match criteria
rm: cannot remove 'metadata/watchdog*-2.4.36.0*xml': No such file or directory
Finding files on remote cloudsmith repository
./download_xml_bash.sh: line 38: wget: command not found
Downloading files found that match criteria
Files downloaded
ls: cannot access 'metadata/watchdog*-2.4.36.0*xml': No such file or directory

=====================

https://cloudsmith.io/~opencpn/repos/logbookkonni-prod/packages/

Is it because of the darn  "v" in the name ?   Logbook-v1.4.22.0-raspbian-9.13-tarball 
```
fcgle@Hesper MINGW64 ~/source/plugins (master)
$ ./download_xml_bash.sh Logbook 1.4.22.0 opencpn prod
Issuing command: wget -q -O - https://cloudsmith.io/~opencpn/repos/Logbook-prod/packages/?q=*1.4.22.0*.xml
Show current files that match criteria
ls: cannot access 'metadata/Logbook*-1.4.22.0*xml': No such file or directory
Deleting current files that match criteria
rm: cannot remove 'metadata/Logbook*-1.4.22.0*xml': No such file or directory
Finding files on remote cloudsmith repository
./download_xml_bash.sh: line 38: wget: command not found
Downloading files found that match criteria
Files downloaded
ls: cannot access 'metadata/Logbook*-1.4.22.0*xml': No such file or directory

```

**Comment by bdbcat** [comment]
Rick...
The tool script "download_xml_bash.sh" has not changed recently.  Been static for months.
Where do you see a new script?
Have you changed how you invoke the script?

**Comment by bdbcat** [comment]
For logbook, you probably need to say:

`./download_xml_bash.sh Logbook v1.4.22.0 opencpn prod`

**Comment by rgleason** [comment]
Yes, that's what I did up above.

`   ./download_xml_bash.sh Logbook 1.4.22.0 opencpn prod`

and several tries. I am trying to think what it might be.
It is a new laptop. I've got the ssh key working.  Could it be norton? I'll try turning that off.
Thanks, now I know the script hasnt changed. That helps.

**Comment by rgleason** [comment]
Oh I've got to add the v?  yes because that is the way logbook metadata was built.
but the other two did not work either

$ ./download_xml_bash.sh watchdog 2.4.36.0 opencpn prod
$ ./download_xml_bash.sh celestial-navigation 2.4.36.0 opencpn prod
I'll try again.

**Comment by bdbcat** [comment]
If you will look at Cloudsmith and study the file names for downloading the metadata, you will see that the "v" is required, if that is the way the file was originally uploaded.  Not the same on all plugins, though.
The script has no way to guess.  It is very literal....

**Comment by jongough** [comment]
Look in the cloudsmith repository "celestial-navigation-prod" only has files up to 2.3.6.0, there is no 2.4.36.0 in these repositories, so what you are doing is reporting correctly. You need to ensure that the build process did upload the files to cloudsmith and which repository they were uploaded too.

**Comment by jongough** [comment]
The logbook issue is to do with case as well as name. You have used "Logbook" in the command but should have used "logbookkonni" in the command. I have just done this and it did download the files, but then has an issued due to the case sensitivity and cannot list the files it downloaded.

**Comment by rgleason** [comment]
Thats pretty dumb. Did we rename the plugin yet?  The files are named Logbook and we use logbookkonni?  I guess this should be fixed. Thanks Jon
Since tbe computer is new there might be a path problem too, but it looks lik python is working... So what did I do wrong with watchdog and cel nav?

**Comment by rgleason** [comment]
Jeez, sorry. Redfaced. Closing

**Comment by rgleason** [comment]
Jon,
I still seem to be having an issue, perhaps with configuration.
I do have pyton available  
```
 ~/source/plugins (master)
$ python --version
Python 3.10.0

```
However when I execute  (now correct) at the bash prompt in  my local  plugins/ repository
$ ./download_xml_bash.sh celestial-navigation 2.3.6.0 opencpn prod
$ ./download_xml_bash.sh watchdog 2.4.36.0 opencpn prod
$ ./download_xml_bash.sh logbook v1.4.22.0 opencpn prod

I get this type of message for all three tries
```
Issuing command: wget -q -O - https://cloudsmith.io/~opencpn/repos/celestial-navigation-prod/packages/?q=*2.3.6.0*.xml
Show current files that match criteria
ls: cannot access 'metadata/celestial-navigation*-2.3.6.0*xml': No such file or directory
Deleting current files that match criteria
rm: cannot remove 'metadata/celestial-navigation*-2.3.6.0*xml': No such file or directory
Finding files on remote cloudsmith repository
./download_xml_bash.sh: line 38: wget: command not found
Downloading files found that match criteria
Files downloaded
ls: cannot access 'metadata/celestial-navigation*-2.3.6.0*xml': No such file or directory

```

What could  I be missing from the configuration?

**Comment by rgleason** [comment]
Why can't ls access metadata/celestial-navigation......
Does this machine need to register with Cloudsmith with an ssl certificate?  I don't think so, it is a public repos.

**Comment by rgleason** [comment]
I've turned Norton Firewall off and it still is doing this.

**Comment by rgleason** [comment]
I've given up on running this script. It just doesn't work for me. So I an downloading by hand. It takes less time than messing with this.

**Comment by rgleason** [comment]
Alec reports these changes to the script.
- No. Only Jon has commits in that script, he seem to be maintaining it.
- BTW: Last change was June 20, so whatever changed it isn't that script
- EDIT: It is actually updated Oct 19 in the master branch by Mauro, but he just fixed the permissions.

Could this be the problem?

**Comment by jongough** [comment]
The script is working as expected.

It looks for already existing entries in metadata that match the criteria you have given it. Then it will try to delete any current items that match these criteria. It's a dumb script and was knocked up quickly to easy the process of downloading and handling multiple build files. Hence it just does an 'ls' to show what is found and an 'rm' to remove any that exist in the directory. This is not a problem.

You don't have wget installed on you linux machine, so you need to install it using whatever package manager you prefer to use. Then the command will work.

The final 'ls' shows what files you have downloaded and have stored in the metadata directory.

I use this script along with the './validate_xml.sh' script to make sure everything is OK before staging, committing and pushing the changes to the relevant part of the plugins git.

However, there is no compulsion to do any of this, it is totally up to you how you handle the updates to plugins.

Not sure why this is an issue for testplugin_pi though, as it is only relevant to the plugins project.

**Comment by rgleason** [comment]
Good discription of the PIM Upload to opencpn/plugins process

`You don't have wget installed on you linux machine, so you need to install it using whatever package manager you prefer to use. Then the command will work.`

That's the problem !  Should have thought of that.

Prerequisites for windows:
install chocolatey    
Install python 3.5 or 310
install wget 

Thank you.

**Comment by rgleason** [comment]
Jon you can close this.

**Comment by rgleason** [comment]
PS: Jon, Just so you know, the scripts are invaluable.
