### ISSUE TITLE
Findit_pi  questions

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#208]
1. Not using JSON validation for this simple one.
   - So have commented out set(EXTSRC  and set(EXTINCLUE
   - Have not copied any of those files over to findit_pi
   
2. Have copied the relevant files from OCPNSRC and OCPNHDRS but have commented out TexFont.cpp and TexFont.h because Findit does not use those.

```
set(OCPNSRC
    ocpnsrc/cutil.cpp
#    ocpnsrc/TexFont.cpp
)
# Findit does not use TexFont.h or TexFont.cpp, so commented out.

set(OCPNHDRS
    ocpninclude/cutil.h
#    ocpninclude/ocpn_plugin.h
    ocpninclude/pluginmanager.h
    ocpninclude/shaders.h
#    ocpninclude/TexFont.h
    ocpninclude/vector2D.h
    libs/ocpn-api/ocpn_plugin.h
)

# Findit does not use TexFont.h or TexFont.cpp, so commented out.
# EXTSRC and EXTINCLUDED not needed no JSON Validation
```

It builds and works right now.

What additional is required to build Android now?

**Comment by rgleason** [comment]
Also don't need ODAPI.h because it does not communicate with Ocpn-Draw so did not use those files in extinclude and extsrc and commented out those sections in cmakelists.txt

In EXTINCLUDE is  GLES2  needed for android?

**Comment by rgleason** [comment]
It is building on master now.  Still have cleanup and fix the icons to do. Maybe other things too.

**Comment by rgleason** [comment]
https://github.com/rgleason/FindIt_pi

**Comment by jongough** [comment]
For android just try a build and see what goes wrong. Doing a 'circleci local' build will make the process much easier and quicker to identify if there is anything missing. Each plugin in unique in what it needs, so there is no real formula except suck it an see.

I notice you have a failure on the macos build, so there is a coding change needed there.
