### ISSUE TITLE
No ocpnsrc/glu/include ?

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#209]
Shouldnt this now be 

`# include_directories(BEFORE ${PROJECT_SOURCE_DIR}/ocpnsrc/glu/include)`

**Comment by jongough** [comment]
It is redundant as glu is now a lib and is handled by the use of 'USE_LOCAL_GLU'

**Comment by rgleason** [comment]
Thanks, so if USE LOCAL_GLU is yes, we should be sure that glu is in lib!
Maybe that should be a note in the CMake file?

**Comment by jongough** [comment]
Yep, as it has to be somewhere it can be found. In the past OCPN would have provided this.

**Comment by rgleason** [comment]
Actually I like glu being in libs.   If we could have a note  in CMakeLIsts.txt at  USE_LOCAL_GLU
# requires  libs/glu files.   

That would help.  When should this be turned on normally?

**Comment by rgleason** [comment]
I have been totally puzzled by this messy historical situation and have been reluctant to change anything.

```
# Use local version of GLU library requirees libs/glu
set(USE_LOCAL_GLU TRUE)
# Prefer libGL.so to libOpenGL.so, see CMP0072
set(OpenGL_GL_PREFERENCE "LEGACY")
# Don't use local version of GLU library
# set(USE_LOCAL_GLU FALSE)
```

Much of this is inherited, but what should be done to clean it up?
And when should I be turning on and off  Local_GLU?
Also when does OpenCP_GL_Preference "LEGACY" get used?  -All the time?   What is it for?

**Comment by jongough** [comment]
This is legacy and I don't use it in my plugins, but some that used Pavel's iteration of the cmake process may still do. I used Pavel's cmake process when building my plugins initially and then morphed it into this version. So, for me, it can be safely removed.

**Comment by rgleason** [comment]
So what can be removed from your Textplugin_pi CMakeLists.txt now,
assuming a current TP template version?
- set(OpenGL_GL_PREFERENCE "LEGACY")   ??

I would  also remove this from Textplugin_pi CMakeLists.txt
# Don't use local version of GLU library
# set(USE_LOCAL_GLU FALSE)

and leave this
# Use local version of GLU library requires libs/glu,  or FALSE
set(USE_LOCAL_GLU TRUE)  

Then the question I have, is what does this affect about the operation of the plugin?
If it is TRUE then does the plugin require OpenGL Acceleration to work?

**Comment by jongough** [comment]
I am updating the build as the android docker image has changed because the current one is deprecated. I am in the process of testing, so am not uploading anything at the moment. I have already removed the line you refer too.

My plugins don't require OGL Acceleration, but it can be used. Other plugins will vary.

**Comment by rgleason** [comment]
This is what I now have in dashboard_tactics_pi

```
# Use local version of GLU library ( libs/glu ), FALSE or TRUE  <--- Clarification notes
set(USE_LOCAL_GLU FALSE)
# Prefer libGL.so to libOpenGL.so, see CMP0072  <--- This can be removed now?
# set(OpenGL_GL_PREFERENCE "LEGACY")      <--- This can be removed now?

option(USE_GL "Enable OpenGL support" ON)   <--- Now what is this?
message(STATUS "${CMLOC}USE_GL: ${USE_GL}")   <--- Just a message output

```
Is  USE_GL  ON  still used?  Is that for OpenGL then?
How is it different than    set(USE_LOCAL_GLU  FALSE or TRUE)  ?

**Comment by jongough** [comment]
USE_GL is used in the cmake files as control logic. USE_LOCAL_GLU is used to add the libs/glu stuff into the build. They are similar but different.

**Comment by rgleason** [comment]
Thanks

Does set(USE_LOCAL_GLU  have to be TRUE )
before  option(USE_GL can be set to ON)?

**Comment by rgleason** [comment]
Now have  in dashboard_tactics_pi  cmakelists.txt

# Adds local version of GLU Library, Adds libs/glu into the build. They are similar but different.
set(USE_LOCAL_GLU TRUE)

```
# USE_GL is used in the cmake files as control logic.
option(USE_GL "Enable OpenGL support" ON)
message(STATUS "${CMLOC}USE_GL: ${USE_GL}")
```

**Comment by jongough** [comment]
The use of USE_LOCAL_GLU says to build the libs/glu, if it is not on then the plugin is relying on the platform having this capability. Some plugins do not work with OpenGL so could not be built with that capability so needed to use USE_GL "OFF". My plugins use both of these as they work with OpenGL and build the libs/glu version. Each plugin is different and needs to be treated as such and tested.

**Comment by rgleason** [comment]
Thanks, have added

```
# Cmake adds local version of GLU Library (libs/glu) into the build.  No "include_directory" needed.  Each plugin is different and needs testing to see if it supports opengl.
set(USE_LOCAL_GLU TRUE)
```

**Comment by rgleason** [comment]
Will need to keep this in mind.
