### ISSUE TITLE
Flatpak Builds - possible fix

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#21]
Jon what is the difference with 

https://github.com/rgleason/testplugin_pi/runs/518080160
which builds flatpak  and master which does not.

**Comment by rgleason** [comment]
It looks like 
ci/circleci-build-flatpak.sh  files are the same. but commented out PLUGIN-bsb4
.circleci/config.yml    did not have line 116 run:   chmod line so I commented it out
.ci/circleci-upload.sh   refers to cmake/in-files/circleci-upload.sh.in
      commented out line 5   chmod
cmake/in-filles/circleci-upload.sh.in  has lines 41-44 commented out unlike the one that works.
     So I am going to try adding that method back in.

**Comment by rgleason** [comment]
Yes, Those changes fix flatpak builds.

**Comment by jongough** [comment]
But I think it breaks the other ones as pyenv versions 'works' but pyenv  global 3.7.0 fails. So I commented it out to get the rest working.

**Comment by rgleason** [comment]
That's interesting. Everything built I thought, except as you will see from 
the other Issue https://github.com/jongough/testplugin_pi/issues/22
I am having trouble with 3 files.  
1.  bionic gtk3 needs to be named properly because currently it is the same name as bionic.
2. raspbian armhf   two builds  seem to be missing.

**Comment by jongough** [comment]
All files now have the OCPN_TARGET in the name. seems a bit of doubling up, but that is what happens when you try to cater for all cases and are building your own package manager. At least it will be automatic.

working on flatpak currently. When that works I will look at the armhf stuff.

**Comment by jongough** [comment]
Flatpak is now working, working on armhf

**Comment by rgleason** [comment]
I'll close this now.
