### ISSUE TITLE
autopilot_route  build errors  related to NMEA0183

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#210]
Cannot seem to figure this one out.

NMEA0183.lib    the "int g_NMEAAPBPrecision"  should probably be defined somewhere.
I have searched for "int g_NMEAAPBPrecision"  in src, include, ocpnsrc, ocpninclude, extsrc, and extinclude, and libs  and have not found it. 

I have switched from using src/nmea0183  to using libs/nmea0183 from the Opencpn library.
Resulting in:  "unresolved external symbol int g_nmeaapbprecision"
I believe the problem is related to[ Nmea 2.3 third paragraph](https://gpsd.gitlab.io/gpsd/NMEA.html#_sentence_mixes_and_nmea_variations)

 `In NMEA 2.3, several sentences (APB, BWC, BWR, GLL, RMA, RMB, RMC, VTG, WCV, and XTE) got a new last field carrying the signal integrity information needed by the FAA. (The values in the GGA mode field were extended to carry this information as well.) Here are the values:`

So the  apb.obj   is calling for this unresolved symbol where should it be added?
I have pushed my current failing configuration up to https://github.com/rgleason/autopilot_route_pi/tree/update-tp  

unresolved external symbol int g_nmeaapbprecision
``
    Creating library C:/Users/fcgle/source/autopilot_route_pi/build/Release/autopilot_route_pi.lib and object C:/Users/fcgle/source/autopilot_route_pi/build/Release/autopilot_route_pi.exp
NMEA0183.lib(apb.obj) : error LNK2001: unresolved external symbol "int g_NMEAAPBPrecision" (?g_NMEAAPBPrecision@@3HA) [C:\Users\fcgle\source\autopilot_route_pi\build\autopilot_route_pi.vcxproj]
NMEA0183.lib(response.obj) : error LNK2001: unresolved external symbol "class wxString g_TalkerIdText" (?g_TalkerIdText@@3VwxString@@A) [C:\Users\fcgle\source\autopilot_route_pi\build\autopilot_route_pi.vcxproj]
C:\Users\fcgle\source\autopilot_route_pi\build\Release\autopilot_route_pi.dll : fatal error LNK1120: 2 unresolved externals [C:\Users\fcgle\source\autopilot_route_pi\build\autopilot_route_pi.vcxproj]

```

**Comment by rgleason** [comment]
The libs/nmea)183 seemed to be missing the apb.cpp file, so I copied the Opencpn/libs/nmea0183  and that is still getting the same error.

**Comment by jongough** [comment]
I have just tried it and I get a relocation error in the build. It wants -fPIC defined, but this is being done already. So I am not sure what the problem is as I don't get it on OD. Will have a think.

**Comment by rgleason** [comment]
Have found that the apb.cpp is different than the one used by Opencpn. Have a question to Sean about this.
https://github.com/seandepagnier/autopilot_route_pi/issues/15

**Comment by rgleason** [comment]
I seem to have this plugin running with sean's version of the apb.cpp, but he has not responded to my question.  Closing
