### ISSUE TITLE
Build with Circleci locally

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#211]
Jon,  I have used 17,000 of 30,000 credits for this month. It is Nov 4 now!
I need to set up local builds immediately.  I have moved to my new computer now, just in time too, as the other one got really flaky.   Do you have any general/specific instructions for me?

**Comment by rgleason** [comment]
https://github.com/OpenCPN/OpenCPN/discussions/2467

**Comment by rgleason** [comment]
https://circleci.com/docs/2.0/local-cli-getting-started/
https://circleci.com/docs/2.0/local-cli/
https://circleci.com/blog/local-pipeline-development/
https://circleci.com/docs/2.0/local-cli/#run-a-job-in-a-container-on-your-machine

to install circleci CLI  with Chocolatety installed
For windows choco install circleci-cli

to install docker 
yet to be determined.

What will this build?
How do I configure for MacOS build and  Ubuntu and Flatpak?
Do I need a virtualbox and then install circleci CLI and docker in that? Plus what else?

**Comment by rgleason** [comment]
There is an orb for docker https://circleci.com/developer/orbs/orb/circleci/docker
Don't know how to use it yet.

**Comment by jongough** [comment]
I use an Ubuntu based distribution for my desktop and really don't use Windows for much and if I do it is in a virtual machine. So I have no experience doing what you are trying to. However, I sometimes use circleci local on my desktop and sometimes in a virtual ubuntu (when I need 16.04, 18.04 or 20.04 for testing purposes). The process runs faster natively on my desktop, but only because I give it more processors. As the build process uses docker for all builds except 'machine' builds this is not a problem. You just need enough storage for the docker image, the android ones can be >8GB, and a reasonable internet (I don't). If your internet is slow or capacity constrained you can create your own docker images with all the updates applied and use these, it only requires a small change to the 'image' line. I also use an apt proxy cache to speed up and stop downloads when the image is updating its installed packages. This again requires a single line change. With the latest version of frontend2 line 86 tells you how to use it. You will need to change the ip address of the cache.

If you have timesouts with circleci downloading images (it does happen to me on the bigger images) you can just use a docker pull command to download it into the docker cache and then restart the circleci job.

It is confusing at first, but does make sense in the end.

**Comment by rgleason** [comment]
I have two options here:
### Option #1 Old Laptop
1. Take apart and clean my old laptop and thenload Ubuntu 20.04, wiping out my old Windows setup 
2. Set it up to process circleci similar to you  (This will take time)
3. Success depends on if my old laptop had hardware issues or not. (it had something wrong with software or hardware)

### Option #2  New Laptop
1. Setup circleci on Windows and start using it, but for what? I can build for Windows locally.
2. Create a Virtualbox with Ubuntu 20.04 and set up circleci_api etc.

### Questions
1. How would I build for MacOS and Android  using Circleci?
2. What is the advantage of running circleci-api on the virtualbox ubuntu? 
2. Should I go ahead and install Virtualbox and install Ubuntu 20.04?

**Comment by jongough** [comment]
I would use the fastest machine you have and do the whole thing in a virtual machine. If you are using Windows as your base then VirtualBox is the only option I know of, if you are using Linux QEMU/KVM is what I tend to use. However you provision the virtual machines it should all work.

Android builds have to be done by issuing the circleci commands, the ones used in the build, by hand in a ubuntu VM and it will work.

MacOS is 'special' and I have a virtual Mac in both VirtualBox and QEMU that I use , but it is slow and difficult. I normally let circleci build these in the normal way.

You may need two Ubuntu's, 18.04 & 20.04, but seeing as someone is now asking about 21.04 you may need one of those as well for testing.

**Comment by rgleason** [comment]
This is getting more and more involved  virtual machines for linux, and having multile VM's for 18.04 and 20.04 and perhaps 21.04 !
https://www.linux-kvm.org/page/Main_Page
https://www.qemu.org/

I think I am not really ready to commit to this if there is another way.

**Comment by jongough** [comment]
Don't use Plugin Manager, it is this process that introduced all of this. I raised issues around this at the time it was being introduced, but....
Being on a slow, limited internet connection I find it very difficult to do some of this stuff, particularly the testing. Using cloud services to build and store applications is all well and good until the rules are changed. We have seen this with Travis, now we are seeing it with Circleci, when will Appveyor and Cloudsmith change? Lets hope that github doesn't change, but it is owned by Microsoft now, so who knows.

**Comment by jongough** [comment]
If you are happy using VirtualBox then continue to do so. It does work and is well supported and shouldn't be an issue. I have both environments because Windows works better on VirtualBox, Linux (at least for me) works better on Qemu.

**Comment by rgleason** [comment]
Jon, my wife was loosing keys on our 12 year old laptops, so she bought 2 new ones. I have finally moved to the new one as mine was getting very flakey and I think needs to be taken apart and dust blown out and a totally fresh OS install. I was thinking I could install Ubuntu rather than Win10, which would avoid a VM, but perhaps I will need the VM anyway?

**Comment by jongough** [comment]
It depends. If you install Ubuntu (or one of the derivatives) on the old machine I would use a light weight desktop such as LXDE (i.e. [https://lubuntu.net/](https://lubuntu.net/)) or XFCE ([https://www.xfce.org/](https://www.xfce.org/)) as you wont be doing much heavy graphics or looking for a full bells and whistles desktop. I would then install QEMU/KVM or VirtualBox to allow running 'disposable' operating systems like Ubuntu of different flavours. This will allow building/testing on different platforms and can be snapshot'd if you need to recover or can be deleted and rebuild without impacting on your machine. You should also install docker and circleci local as well as  git to allow building of most varieties of supported systems.

I would stay clear of windows, of any flavour, as it is likely to have higher hardware requirements. You also don't need virus checkers as you will be running 'isolated' on the laptop so it is highly unlikely you will get one. Using either QEMU/KVM or Virtualbox it is possible to install a runnable MacOS ( not fast, not flash and there may be 'quirks', but...) to build and test on that environment as well.

**Comment by rgleason** [comment]
Jon, thank you. 

I looks like lubuntu is the entire OS and XFCE (which I think I used with a Windows10 WSL  linux/bash install early on) is a desktop running on something like Ubuntu 20.04? Or should I install something like Ubuntu 12?.  What are you using?

The lubuntu install looks pretty good, one simple installation. It looks like the 2010 Dell Inspiron XPS L502x will meet requirements i7- 720QM 2.20 GHz Turbo Boost 2.0 up to 3.30 GHz,   8gb ram, Geforce Nvidia NVIDIA GeForce GT540M 2GB, 500gb SSD...There may be some graphics hiccups I've read about. I guess I download the image and get it on a USB drive. Then mount that drive on the subject computer and then execute. all after I take it apart and clean it and add heat transfer paste to the cpu and graphics card.  Found this about install on a Dell Laptop https://gist.github.com/cantbewong/e2fa21603633bfe2c3a500bdcc853988  also[ clean install from Tom's hardware](https://forums.tomsguide.com/faq/how-to-install-linux-ubuntu-14-04-on-the-dell-xps-13-2-in-1.412935/)

[QEMU](https://www.qemu.org/) Is opensource command line virtualizer
[KVM](https://www.linux-kvm.org/page/Main_Page) is opensource and it looks like QEMU uses KVM!
So when you suggest  QEMU/KVM  I would install just from QEMU?

Of course I am quite familiar with [Oracle Virtualbox](https://www.virtualbox.org/) so I may just use that.

**Comment by jongough** [comment]
If you can boot from a USB device you can boot most Linux systems from the USB to give it a go. You can then try installing the required packages and see if you can make it work. This avoids installing fully something that is no good. Once you have ascertained that the version of Linux you are using is OK then you can do the full install from the USB (it should be one of the options after booting from the USB stick). I only suggested lubuntu as it is a complete lightweight system. You could use standard Ubuntu but with the XFCE desktop and again it should be lightweight. I use Linux Mint Cinnamon which is a bit heavier, but I use it on my main machine which is resourced to handle what I need.

Using Ubuntu or a Ubuntu based distribution is probably the safest as all the OCPN builds will work on it, the system is up to date and is actively maintained. Debian is another but I don't like it, although others rave about it. That is why it depends on your tastes and needs. I need something based on Ubuntu to keep the number of base systems down. I use virtual machines for anything that is not Ubuntu and is not the current version I am using. I use both QEMU/KVM (yes, KVM is the virtual machine and QEMU is the UI and control interface) and VirtualBox, both have advantages and disadvantages, but again it is what you are happy with. Both will work for what I think you are doing with OCPN. The most difficult VM is the MacOS which is more convoluted to install and run than the other environments. Android VM's tend to require 'Android Studio' and it creates VM runtimes of its own, but you can simulate phones and tablets all be it slowly and with some quirks. I don't know how to simulate iPhone or iTables (whatever they are called).

So as you are using an old laptop that is not required for anything else you should just give it a go using 'boot from USB' to start with. It will not hurt anything. It will take a bit of time to get it all going, but....

**Comment by jongough** [comment]
Can this issue be closed?

**Comment by rgleason** [comment]
yes sure
