### ISSUE TITLE
TP 1.0.180 and 1.0.179  Json does not work

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#212]
Json validation has been a problem for awhile, errors compiling. Some path is not right.

 Therefore, to simplify, I am going to remove it.

**Comment by rgleason** [comment]
It turns out that Dashboard_tactics has two ways of building one as Dashboard_tactics and the other as just Dashboard.  Updating caused disruption in collecting those SRCS and HDRS to get them processed.   I had to add an "S" at the end of one of the statements.

For some reason I was getting all kinds of Json validation notices at one point trying to fix this problem.

Closing

**Comment by jongough** [comment]
I have JSON validation turned on and it is not causing any issues on my plugins. There is no compulsion to use JSON validation and it is in the section of CMakeLists.txt that is the responsibility of the plugin developer.

**Comment by rgleason** [comment]
Yes
