### ISSUE TITLE
polar_pi  svg icons not working yet

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#214]
The green puzzle comes up, and I've checked icons.h, icons.cpp and polar_pi.cpp  SVG code and it all looks ok to me. I've tried to get this working for awhile. It is getting better and not crashing OpenCPN now.   I think it is perhaps something else that is causing the problem.

The branch is master-update  https://github.com/rgleason/polar_pi/tree/master-update
I've disabled the circleci builds.

**Comment by rgleason** [comment]
I've updated it and tried to improve it following findit   findit_pi.cpp  but the svg icons are still not appearing.

**Comment by jongough** [comment]
Check the OCPN log, if it cannot find the files it will tell you there where it is looking for them. This may give a hint as to what is wrong.

**Comment by rgleason** [comment]
Good idea!
I changed  %localappdata%/opencpn/plugins/Polar_pi to  "polar_pi"  and started O and the icon appeared in the toolbar!
all because of a capital "P"!!   That has happened 3x's now.  Thanks.
```
20:09:56.977 MESSAGE pluginmanager.cpp:1149 Checking plugin candidate: C:\Users\fcgle\AppData\Local\opencpn\plugins\plots_pi.dll
20:09:56.977 MESSAGE pluginmanager.cpp:1200 Skipping not enabled candidate.
20:09:56.977 MESSAGE pluginmanager.cpp:1149 Checking plugin candidate: C:\Users\fcgle\AppData\Local\opencpn\plugins\Polar_pi.dll
20:09:56.993 MESSAGE pluginmanager.cpp:2195 Plugin is compatible: true
20:09:56.993 MESSAGE pluginmanager.cpp:2284 PlugInManager: Loading PlugIn: C:\Users\fcgle\AppData\Local\opencpn\plugins\Polar_pi.dll
20:09:57.008 MESSAGE OCPNPlatform.cpp:1674 Using private plugin dir: C:\Users\fcgle\AppData\Local\opencpn\plugins
20:09:57.008 MESSAGE OCPNPlatform.cpp:1623 Using plugin data path: C:\Users\fcgle\AppData\Local\opencpn\plugins;C:\Program Files (x86)\OpenCPN\plugins
20:09:57.008 MESSAGE pluginmanager.cpp:553 PlugInManager: Using data dirs from: C:\Users\fcgle\AppData\Local\opencpn\plugins;C:\Program Files (x86)\OpenCPN\plugins
20:09:57.008 MESSAGE pluginmanager.cpp:572 Warnińg: no data directory found, using ""
20:09:57.008 MESSAGE icons.cpp:31 Loading toolbar icon: data\polar.svg
20:09:57.008    INFO pluginmanager.cpp:2460 PlugInManager:  C:\Users\fcgle\AppData\Local\opencpn\plugins\Polar_pi.dll
20:09:57.008    INFO pluginmanager.cpp:2461         Plugin common name: Polar
20:09:57.024    INFO pluginmanager.cpp:2463         API Version detected: 116
20:09:57.024    INFO pluginmanager.cpp:2464         PlugIn Version detected: 1.1
```

**Comment by rgleason** [comment]
I believe the culprit was fixed sometime ago, in icons.cpp, however the directory was never cleaned out, so the "Polar_pi" directory stayed in place, leading to the icons not loading!  So the moral is to remove all associated directories and dlls if you have a "capital" in your plugin name pathway.  

Then reinstall the plugin again and test!

**Comment by rgleason** [comment]
In CMakeLists.txt  changed  package and  verbose name to "polar"

**Comment by jongough** [comment]
This can happen as Linux is case sensitive and windows tends not to be for file and directory names. I 'think' this may have changed with Win 10, or at least you can set something in the registry to make it case sensitive. So windows used to say that Polar and polar are the same but Linux (unix) have said they are different and normally only apply the windows rules when using Samba for file shares.

**Comment by rgleason** [comment]
Very internesting and important to keep in mind.  I have recently had several of these types of problems. Thanks.
