### ISSUE TITLE
For next version - correction

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#215]
set(LIBHDRS
    libs/GL/gl.h
    libs/GL/gl_private.h
    libs/GL/glext.h
    libs/GL/glu.h
    libs/wx/include/json_defs.h    <--- libs/wx  does not exist, I believe it is now wxJSON
    libs/wx/include/jsonreader.h  <---Same
    libs/wx/include/jsonval.h   <---Same
    libs/wx/include/jsonwriter.h)  <---Same

**Comment by rgleason** [comment]
Also

set(OCPNHDRS
    ocpninclude/cutil.h
#    ocpninclude/ocpn_plugin.h     <---exists in   libs/ocpn-api/ocpn_plugin.h

**Comment by rgleason** [comment]
I don't find this here does not exist in testplugin
include_directories(BEFORE ${PROJECT_SOURCE_DIR}/ocpnsrc/glu/include)
perhaps it is supposed to be pointing to libs/glu?

What is this for?  Android?

**Comment by jongough** [comment]
Be mindful of the section of the CMakeLists.txt that this exists in. This should be in the plugin section not the frontend2 section. OD uses that to give access to the header files for GLU whilst building glu in the libs section to be included at link time. As frontend2 is a standardised build to help for all platforms it hides most of the complexity of the process, but it cannot determine what each plugin requires to be built for it to be successful and functional. I have attempted, however poorly, to make this plain in the cmake files. There may be bits I have not cleaned up successfully at the moment for my plugins, but this should not, hopefully, impact other plugins using the frontend2 process.

Frontend2 follows my preferred approach to separating items out so that I know where 'borrowed' bits come from and which I should not change without consciously doing so and incorporating the changes into the plugin, i.e. by addind OD to the module name.

**Comment by rgleason** [comment]
Jon, I still don't have a clear idea of what is needed when.
Can you identify which of these are needed to build Android, for example?
And which ones are not needed for very simple plugins?
For example, AISradar currently has all of these commented out and it builds everything except android.

```
#set(OCPNSRC
#    ocpnsrc/cutil.cpp
#    ocpnsrc/TexFont.cpp
#)

#set(OCPNHDRS
#    ocpninclude/cutil.h
#    ocpninclude/ocpn_plugin.h
#    ocpninclude/pluginmanager.h
#    ocpninclude/shaders.h
#    ocpninclude/TexFont.h
#    ocpninclude/vector2D.h
#    libs/ocpn-api/ocpn_plugin.h
#)

#set(EXTSRC
#)

#set(EXTINCLUDE
#    extinclude/ODAPI.h
#    extinclude/ODJSONSchemas.h
#)

#set(LIBSSRC libs/wxJSON/src/jsonreader.cpp libs/wxJSON/src/jsonval.cpp libs/wxJSON/src/jsonwriter.cpp)

#set(LIBHDRS
#    libs/GL/gl.h
#    libs/GL/gl_private.h
#    libs/GL/glext.h
#    libs/GL/glu.h
#    libs/wxJSON/include/json_defs.h
#    libs/wxJSON/include/jsonreader.h
#    libs/wxJSON/include/jsonval.h
#    libs/wxJSON/include/jsonwriter.h)
```

**Comment by jongough** [comment]
Basically, none are needed it depends on what the plugin does and what it needs to interact with. If it is using JSON at all and want to send and receive those messages it will need the wxJSON stuff. If it wants to use graphics is may need TexFon and some graphics libraries, but again it depends on what the plugin is trying to do and what capabilities it needs. Unless the plugin is going to validate OD JSON messages against a schema it does not need the ODJSONSchema stuff. The ocpn-api header file will be needed or the plugin cannot interact with OCPN in any way.

Android only changes the wxWidgets code and the graphics code. Again, it depends on what the plugin does. OD does more than testplugin, but all my plugins have at least one UI graphical element that is needed, most have two, i.e. settings and runtime dialog boxes, etc.

**Comment by rgleason** [comment]
`Android only changes the wxWidgets code and the graphics code.`
- Ok what is the graphics code that is needed?
- Do we have to include anything, like libs/glu files?
- Don't we have to also have an include_directory to the libs/glu for android?
- What else is necessary for android builds?

Are these comments right?

```
# These are files Ocpn-Draw uses -Not needed or is this for android?
#set(OCPNSRC

## These are files Ocpn-Draw uses - Not needed or is this for android?
#set(OCPNHDRS

# Needed for what?
#set(EXTSRC

# Needed to use ODAPI messaging in the plugin  (ODraw, Watchdog, Weather_routing & Squiddio)
#set(EXTINCLUDE

# Use if the plugin needs JSON messaging then it needs wxJSON, for json validation include the cmake statements.
#set(LIBSSRC 

# Use if the plugin needs JSON messaging then it needs wxJSON .  Also if the plugin needs "local" GL
#set(LIBHDRS
```

**Comment by jongough** [comment]
Android uses different wxWidgets implementation and these changes are in the master.zip file that Dave provides. If the plugin is going complicated graphics, i.e. tessellation, then the plugin will have to have android specific code to build and run and this code will have to exist within #ifdef #endif statements. For an example see OD - Boundary.cpp lines 334-393. Nothing is necessary for android builds unless the particular plugin needs it. OD has different needs to testplugin. Each plugin is unique in this respect, so will require custom changes if it fails to build or run. If it builds and runs with no changes then all is good, if not it will require debugging to determine what has to be updated. It really is 'suck it and see'.

OCPN* indicates OCPN files that are needed by the plugin to build and run. 
EXT* indicates extra files that use third party source and headers needed by the plugin to build and run
LIB* indicates files that should exist in libs and have their own CMakeLists.txt file to build them. In some cases these have not yet been generated but the code has been moved to the LIB* location to follow the current thinking/standard for plugins.

If a plugin has changed texfont.h and texfont.cpp then in my plugins I would have re-named them, i.e. ODtexfont.*, to indicate that they were no longer the same as the originals and that they need to be maintained by the plugin developer. Having them as texfont.* would mean that the plugin needs them but they are maintained by someone else and the files can just be copied over with newer versions. If they then fail to work the old version would be renamed. What a plugin developer decides to do is up to them. So if they have been changed, I have no idea how to maintain them. You would need to ask the developer or do build and testing to see what happens.

**Comment by rgleason** [comment]
Thank you.  I guess OCPN refers to OpenCPN , not OCPN_draw
In many cases I have not been using the OCPNSRC and  OCPNHDRS, but the plugin must be setup differently.
I will look at this more carefully.

EXT extra 3rd party files, include JSON and ODAPI?

**Comment by jongough** [comment]
ODAPI is the OCPN_Draw binary API roughly equivalent to the OpenCPN binary API which allows other plugins to talk to OCPN_Draw through a binary interface (at least three plugins use this interface). There is also a JSON API interface that has to be used to get the binary interface addresses. The JSON API allows the same functionality as the binary interface. For robustness OCPN_Draw has implemented JSON schema validation and has made this validation available to the other plugins to use if they want to. Testplugin_pi uses both of the interfaces to test to make sure they work and therefore show how to use JSON schema validation.

The JSON schema validation is provided by a third party product and therefore is external to OCPN_Draw and in the EXT* labels. For testplugin the ODAPI is external, i.e. part of the OCPN_draw plugin, and therefore is in the EXT* labels.

**Comment by rgleason** [comment]
This include_directory has moved to libs so this does not exist.

include_directories(BEFORE ${PROJECT_SOURCE_DIR}/ocpnsrc/glu/include)

**Comment by jongough** [comment]
I think you may be using an old version, this is not in the current version 1.0.181.0 .

**Comment by rgleason** [comment]
I am!  when did you update it? --never mind.  Thanks.

**Comment by jongough** [comment]
I am fighting circleci making changes to the locations of part of the system and cloudsmith changing bits as well. I am just trying to get a new version of testplugin and OD working (with the new icons). The new build process will be a never ending story of continuous upgrades which will require tweeks far more frequently than I had hoped. There seems to be little stability in the cloud build environments, mores the pity.

**Comment by rgleason** [comment]
Jon, I've just updated a whole lot of the plugins.  Should I update those plugins?   
Also out of curiosity what is ndk?  
I hope they will complete quicker.

**Comment by jongough** [comment]
If they build that is fine, but my android builds failed with the new docker image that is supplied by circleci. They moved the position in the file system of required libraries, they used to be in /opt/android, now they are in ~/.android* . 

[https://developer.android.com/ndk/](https://developer.android.com/ndk/)

**Comment by rgleason** [comment]
Very interesting, but I've got to learn to walk first!

**Comment by jongough** [comment]
That is the point of frontend2, you don't need to do the investigation, you just have to use it. For me of course.....

**Comment by jongough** [comment]
New version 1.0.183.1 is not in master which fixes issues with the new images that circleci is using and the xml for darwin-wx315. I think this version should now be used. The upgrade for plugins should be just a copy of the frontend2 files over the ones currently in use for the plugins.
