### ISSUE TITLE
Tactics_pi  xenial error

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#218]
https://app.circleci.com/pipelines/github/rgleason/tactics_pi/33/workflows/a98b7b50-6a3b-455a-a101-ecda632b270c/jobs/367

What should I do?

https://github.com/rgleason/tactics_pi

**Comment by rgleason** [comment]
Now it says it has completed. That is a bit weird. Closing

**Comment by jongough** [comment]
I sometimes rerun the failed build if it does this and if it works it was a circleci problem, if it fails a second time it 'may' be a frontend2 problem. I would then normally try again with circleci local and check what happens. I can then use docker to see what happens to the installation process.

Not overly helpful, but we are not in control of these environments and they do have issues at times. Just have to put up with it.
