### ISSUE TITLE
O fail when Polar_pi is  disabled in PIM

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#220]
Jon, I have three plugins that crash O when disabled and they are the next thing to fix.

- Polar 1.1.22.0 +1.0.180 [branch master ](https://github.com/rgleason/polar_pi/tree/master)Disabled Android. Prod in Master 10/20/2021 svg icons fixed 11/14/2021 Fails O
- Climatology 1.4.33.0 +1.0.180 [branch maste](https://github.com/rgleason/climatology_pi/tree/master)r Prod in Master icons centered & improved 11/16/202 when disable. OpenCPN Fails Also About take ages to load.
- LogbookKonni 1.4.22.0 + SD 2.8.7.2 plus [branch master](https://github.com/rgleason/LogbookKonni_pi/tree/master) leamas cleanup. Prod in master 10/31/2021

I'd really appreciate your help with the first one,  polar_pi if you can find the time.   It once had the ancient plugin interface where the PI turned its toolbar Icon on and off, that is no longer the case so there are lots of commented out like this one in polar_pi.cpp at line 451

`           //pConf->Read ( _T( "ShowPolarIcon" ),  &m_bPolarShowIcon, 1 );`

The plugin has a lot of commented out lines and is somewhat messy in that respect.
I think the problem is related to the handling of this boolean.  Somehow when we un - enable  the plugin in OpenCPN, there is a conflict which causes OpenCPN to fail.

I am going to look at Climatology to see if I can figure that one out.

**Comment by rgleason** [comment]
Climatology has code like this from shipdriver. I am wondering if there should be an  "end" to the "if statement?

 ```
   wxLogDebug(wxString("Using icon path: ") + path);
    if (!wxImage::CanRead(path)) {
        wxLogDebug("Initiating image handlers.");
        wxInitAllImageHandlers();
    }
    wxImage panelIcon(path);
    if (panelIcon.IsOk())
        m_panelBitmap = wxBitmap(panelIcon);
    else
        wxLogWarning("ShipDriver panel icon has NOT been loaded");
    m_bShowShipDriver = false;
    ---should there be an "end" here, or something?
```

**Comment by rgleason** [comment]
The closing of climatology seems to center around line 308 of climatology_pi.cpp, but is this just about the menu dialog, not the toolbar icon?

```
void climatology_pi::OnClimatologyDialogClose()
{
    if(m_pClimatologyDialog) {
        if(m_pClimatologyDialog->m_cfgdlg)
            m_pClimatologyDialog->m_cfgdlg->Hide();
        m_pClimatologyDialog->Show(false);
        RequestRefresh(m_parent_window); // refresh main window
    }
    SaveConfig();
}
```

**Comment by jongough** [comment]
No, the 'if' is a 'single line' as is the 'else'.

> Climatology has code like this from shipdriver. I am wondering if there should be an "end" to the "if statement? climatology_pi [ src/climatology_pi.cpp ](https://github.com/rgleason/climatology_pi/blob/master/src/climatology_pi.cpp) starting at about line 87 I've used it in many plugins and it seems to work fine as it is...
> 
> ```
>   wxLogDebug(wxString("Using icon path: ") + path);
>    if (!wxImage::CanRead(path)) {
>        wxLogDebug("Initiating image handlers.");
>        wxInitAllImageHandlers();
>    }
>    wxImage panelIcon(path);
>    if (panelIcon.IsOk())
>        m_panelBitmap = wxBitmap(panelIcon);
>    else
>        wxLogWarning("ShipDriver panel icon has NOT been loaded");
>    m_bShowShipDriver = false;
>    ---should there be an "end" here, or something?
> ```

**Comment by rgleason** [comment]
In polar_pi.cpp  there are these lines which don't make sense.

```
// This one does not look right ENGINEBUTTON   Enginestatus???
void polar_pi::SetPluginMessage(wxString &message_id, wxString &message_body)
{
      if(message_id == _T("LOGBOOK_ENGINEBUTTON1"))
      {
		if(m_pPolarDialog)
			m_pPolarDialog->polar->setEngineStatus(message_body);
      }
}

```

Ok, so this is what Polar_pi has 


```
polar_pi::polar_pi(void *ppimgr)
      :opencpn_plugin_116(ppimgr)
{
      // Create the PlugIn icons
      initialize_images();
	  
 // From shipdriver to read panel icon file
    wxFileName fn;

    auto path = GetPluginDataDir("polar_pi");
    fn.SetPath(path);
    fn.AppendDir("data");
    fn.SetFullName("polar_panel.png");

    path = fn.GetFullPath();

    wxInitAllImageHandlers();

    wxLogDebug(wxString("Using icon path: ") + path);
    if (!wxImage::CanRead(path)) {
       wxLogDebug("Initiating image handlers.");
       wxInitAllImageHandlers();
    }
    wxImage panelIcon(path);
    if (panelIcon.IsOk())
       m_panelBitmap = wxBitmap(panelIcon);
    else
       wxLogWarning("Findit panel icon has NOT been loaded");
       m_bPolarShowIcon = false;
 // End of from Shipdriver	  
	  
}
```

**Comment by rgleason** [comment]
Isn't this what disables the panel icon?

```
 wxImage panelIcon(path);
    if (panelIcon.IsOk())
       m_panelBitmap = wxBitmap(panelIcon);
    else
       wxLogWarning("Findit panel icon has NOT been loaded");
       m_bPolarShowIcon = false;
```

**Comment by jongough** [comment]
Re: [https://github.com/jongough/testplugin_pi/issues/220#issuecomment-976103872](https://github.com/jongough/testplugin_pi
/issues/220#issuecomment-976103872)
It would be normal for a plugin to provide a message_id that said who it was aimed at or from and within that message a 'Msg' giving the qualifier. If you want to see and example look in OD at ODJSON.cpp or testplugin at tpJSON.cpp both of which deal with JSON messages coming in through the SetPluginMessage OCPN API.

So with this message I have no idea who is sending it. It may be LogbookKonni, but.....

**Comment by jongough** [comment]
The following does seem strange as the setting of false is overridden by setting `m_bPolarShowIcon` to `true` at line 141 in the 'Init' function.

> Isn't this what disables the panel icon? If so, why would it cause O to fail?
> 
> ```
>  wxImage panelIcon(path);
>     if (panelIcon.IsOk())
>        m_panelBitmap = wxBitmap(panelIcon);
>     else
>        wxLogWarning("Findit panel icon has NOT been loaded");
>        m_bPolarShowIcon = false;
> ```

I would have thought this would make more sense:
```
    if (panelIcon.IsOk()) {
       m_panelBitmap = wxBitmap(panelIcon);
       m_bPolarShowIcon = true;
    }
    else {
       wxLogWarning("Findit panel icon has NOT been loaded");
       m_bPolarShowIcon = false;
    }
```
and then remove line 141.

**Comment by rgleason** [comment]
Thank you Jon. I will look more closely tomorrow and try some experiments..

 This afternoon I completely took apart my 10 yr old laptop, cleaned it and the fan which was I think was full of dust from my activities sanding and painting the inside rooms and put new thermal paste.  Now it seems to be running much better and more responsive, but most of all Windows is working right now and not repeating and duplicating website tabs to infinity. It is actually usable.  It is still early, but I think the dust may have been the culprit.  If it works I will just clean it up and install virtualbox again.

**Comment by rgleason** [comment]
The MS Edge multiplying tabs (100's) issue which takes over the computer has reappeared. I will try some fixes and if it fails, start over with Linux.

**Comment by jongough** [comment]
I have moved pretty much everything to Linux because of the issues with MS Windows and its software. I still have virtual machines for testing some of the code, but really don't use it any more because of the continual issues and upgrades that break things and in particular backwards compatibility.

**Comment by rgleason** [comment]
Jon, I am going to close this. I know where to find it for when I reconfig the laptop.
