### ISSUE TITLE
MacOS Issues

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#223]
Jon are you aware of this https://www.cruisersforum.com/forums/f134/opencpn-beta-5-5-1129-released-258367.html#post3531197

I do not have any idea yet what is amiss, but it has something to do with 
https://www.cruisersforum.com/forums/f134/opencpn-beta-5-5-1129-released-258367.html#post3531196

https://www.cruisersforum.com/forums/f134/opencpn-beta-5-5-1129-released-258367-2.html#post3530649

**Comment by rgleason** [comment]
Jon, Please see MacOS script change needed, may affect all plugins using TP

https://github.com/rgleason/climatology_pi/issues/26

**Comment by jongough** [comment]
Fixed by v1.0.184.3 which is currently going through the build process to prod.

**Comment by rgleason** [comment]
Jon Thank you.  You might want to check the PR that Bdbcat made for Climatology. 
https://github.com/rgleason/climatology_pi/commits/master
He added gtk2.0 to control amoungst other things.

**Comment by rgleason** [comment]
Please let me know if this is complete, so I can start fixing MacOS on 20 plugins.

**Comment by rgleason** [comment]
`Fixed by v1.0.184.3 which is currently going through the build process to prod.`
actually I think not, see autotrackraymarine_pi Issues.

**Comment by jongough** [comment]
Currently v1.0.185.0 is going through with the changes for MacOS, gtk2 and opencpn.lib

**Comment by rgleason** [comment]
Thanks. Done
