### ISSUE TITLE
How to cancel circleci job runs?

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#224]
Jon,
Please see https://app.circleci.com/pipelines/github/rgleason/AutoTrackRaymarine_pi/16/workflows/75214b27-0c11-4cd9-b37d-a413d4063438/jobs/108

I have not configured this properly to prevent all job runs and I comes up with an X.
I would like to simply skip all job runs. Is there a way to hard code that in config.yml?

**Comment by jongough** [comment]
You only have to comment out two lines per job you don't want to run. That is the "- build-*" and the following line "<<: *std-filters". You do have to comment out both of these lines as the "<<: *std-filters" is used as input to the build job.

**Comment by rgleason** [comment]
OK I have been commenting out just the "build"

Is there a good way to prevent all builds?  or do I have to comment out all the builds and >>?

**Comment by jongough** [comment]
Why would you stop all builds?
For each build you will need to comment out the build line and the << line.

**Comment by rgleason** [comment]
Because autotrackraymarine fails all linux and mac

**Comment by jongough** [comment]
If there is no intention to make autotrackraymarine work for linux and mac then turn off this capability in github. If you don't want to do that then comment out all the jobs in the build_all workflow. This will cause a circleci yml error when executed but should use very little resources. With the current setup (which you requested) there is no way to cleanly turn off all builds, there has to be at least one to avoid a yaml parsing error.

**Comment by rgleason** [comment]
ok, thanks.
