### ISSUE TITLE
autotrackraymarine_pi  appveyor not deploying

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#225]
Entered cloudsmith_api_key  number under variables in appveyor > autotrackraymarine_pi > settings
so appveyor should be able to deploy to cloudsmith.

Also have changed cloudsmith > autotrackraymarine  repository > Access Controls to add the Plugin Team with Write permissions.

```
+ cloudsmith push raw --republish --no-wait-for-sync --name AutoTrackRaymarine_pi-0.3.4.2-msvc-x86_64-10.0.14393-MSVC-metadata --version 0.3.4.2+21.9bcfb62 --summary 'AutoTrackRaymarine opencpn plugin metadata for automatic installation' opencpn/AutoTrackRaymarine-beta /c/project/ocpn_project/build/AutoTrackRaymarine_pi-0.3.4.2-msvc-x86_64-10.0.14393-MSVC.xml
Checking raw package upload parameters ... ERROR
Failed to validate upload parameters! (status: 404 - Not Found)
Detail: Not found.
Hint: This usually means the user/org is wrong or not visible.
Command exited with code 148
```

Earlier builds before I entered the Cloudsmith key had

```
+ BUILD_BRANCH=master
+ BUILD_TAG=v0.3.3.0
+ PKG_EXT=exe
+ set +x
Cannot deploy to cloudsmith, missing $CLOUDSMITH_API_KEY
Collecting artifacts...
Found artifact 'build\AutoTrackRaymarine_pi-0.3.3.0-msvc-x86_64-10.0.14393-MSVC.exe' matching 'build\*.exe' path
Uploading artifacts...
[1/1] build\AutoTrackRaymarine_pi-0.3.3.0-msvc-x86_64-10.0.14393-MSVC.exe (257,296 bytes)...100%
Build success
```

**Comment by rgleason** [comment]
I am thinking it won't deploy because the packages aren't complete?
But perhaps I am missing a key somewhere?  Due to 

**Cannot deploy to cloudsmith, missing $CLOUDSMITH_API_KEY**
```
Collecting artifacts...
Found artifact 'build\AutoTrackRaymarine_pi-0.3.4.4-msvc-x86_64-10.0.14393-MSVC.exe' matching 'build\*.exe' path
Uploading artifacts...
[1/1] build\AutoTrackRaymarine_pi-0.3.4.4-msvc-x86_64-10.0.14393-MSVC.exe (257,485 bytes)...100%
Build success
```

**Comment by jongough** [comment]
The CLOUDSMITH_API_KEY should be entered in Appveyor/Settings/Environment and an environment variable needs to be created called 'CLOUDSMITH_API_KEY' with the value of the key for access to cloudsmith. It would appear that you are missing the environment variable

**Comment by rgleason** [comment]
I have done this several times and it did not deploy. Then I tried removing the key and it still did not deploy possibly because of failure to fully build issues?. I will try this again.

**Comment by jongough** [comment]
If you are not building the exe file then it cannot be uploaded. Frontend2 still builds the locally installable versions of the plugins, mainly for testing, but also for those that do not want, wish or cannot use Plugin Manager. I had to make changes for an issue raised on this with Frontend2 for someone that was building for the 'non-standard' platforms.

Testplugin built in appveyor, see:
[https://ci.appveyor.com/project/jongough/testplugin-pi](https://ci.appveyor.com/project/jongough/testplugin-pi) current build

**Comment by rgleason** [comment]
I had not enabled it properly in appveyor.
I had to remove the key, close and then add again.
