### ISSUE TITLE
autotrackraymarine_pi  xml_info_url

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#228]
Jon,
I am getting a weird problem with the PIM listing for autotrackraymarine when I hit the  "Website" button for this plugin it goes to "https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:plugins:safety:odraw1.6_pi"

Yet I have in cmakelists.txt this set for the url and I see in the metadata that it is this same URL, so why does it go to ocpn_draw?????

`set(XML_INFO_URL "https://opencpn-manuals.github.io/main/autotrackraymarine/0.1/index.html")`

**Comment by rgleason** [comment]
Here is a recent search

Search "INFO_URL" (3 hits in 3 files of 714 searched)
  C:\Users\fcgle\source\AutoTrackRaymarine_pi\cmake\in-files\plugin.xml.in (1 hit)
	Line 25:   <info-url> ${XML_INFO_URL} </info-url>
  C:\Users\fcgle\source\AutoTrackRaymarine_pi\CMakeLists.txt (1 hit)
	Line 73: set(XML_INFO_URL "https://opencpn-manuals.github.io/main/autotrackraymarine/0.1/index.html")
  C:\Users\fcgle\source\AutoTrackRaymarine_pi\CMakeLists.txt.bak (1 hit)
	Line 73: set(XML_INFO_URL "https://opencpn-manuals.github.io/main/autotrackraymarine/0.1/index.html")

**Comment by jongough** [comment]
I have looked in the beta cloudsmith respository and there is a single xml package for autotrack and it appears to be correct. Not sure what problem you are reporting as the build process would appear to be working.

**Comment by rgleason** [comment]
When I load it into Opencpn and click on "Website" in Preferences, the URL used is  "https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:plugins:safety:odraw1.6_pi"   

It is a little bizarre.

**Comment by jongough** [comment]
How are you loading it, through using a local version of the xml file? I don't have a working windows environment to see the issue at the moment.

**Comment by rgleason** [comment]
Yes, I am building and Importing the plugin locally in Windows.  Thanks Jon for your help and thoughts.

**Comment by rgleason** [comment]
Uploaded manually earlier to check that it works.  Will look into this further tomorrow. Thanks.
`I have looked in the beta cloudsmith respository and there is a single xml package for autotrack and it appears to be correct. Not sure what problem you are reporting as the build process would appear to be working.`

**Comment by rgleason** [comment]
I found that the https://  link in the metadata file was wrong and lead nowhere. This is now fixed. Closing.
