### ISSUE TITLE
TP Auth Keys to Build and Deploy 

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#230]
See this post, for TP most of it is similar.
https://github.com/Rasbats/shipdriver_pi/issues/232#issuecomment-950860578

**Comment by jongough** [comment]
Yup. That is the problem with having two different build processes where one is deliberately obfuscating. This should be in a common area as it is to do with github, cloudsmith, circleci, appveyor and travis, it has nothing to do with a particular build process.

**Comment by rgleason** [comment]
Agree with you completely.
