### ISSUE TITLE
MacOS Fixes

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#231]
**Pushed to PIM**   Updated to TP 1.0.185.0
[Polar 1.1.24.0](https://cloudsmith.io/~opencpn/repos/polar-prod/packages/)
[Pypilot 0.30.3.0](https://cloudsmith.io/~opencpn/repos/pypilot-prod/packages/)
[StatusBar 0.7.15.0 ](https://cloudsmith.io/~opencpn/repos/statusbar-prod/packages/)- PR from Bdbcat
[Watchdog 2.4.39.0](https://cloudsmith.io/~opencpn/repos/watchdog-prod/packages/)
[WeatherFax 0.7.15.0](https://cloudsmith.io/~opencpn/repos/weatherfax-prod/packages/)
[WeatherRouting 1.13.35.0 ](https://cloudsmith.io/~opencpn/repos/weather-routing-prod/packages/)
[Climatology 1.4.38.0 -](https://cloudsmith.io/~opencpn/repos/climatology-prod/packages/) PR from Bdbcat
[GPS Odometer 0.6.6.1](https://cloudsmith.io/~opencpn/repos/gps-odometer-beta/packages/) -Lennart updated to TP 1.0.185  Bdbcat reviewed, Lennart pushing to PIM
[DashboardTactics 1.6.10.0 ](https://cloudsmith.io/~opencpn/repos/dashboardtactics-beta/packages/)  Funny thing version number does not change.
[Plots 2.2.10.0](https://cloudsmith.io/~opencpn/repos/plots-prod/packages/)  - Funny thing version number does not change.
[Squiddio 1.3.17.0](https://cloudsmith.io/~opencpn/repos/squiddio-prod/packages/)
[Autopilot Route 0.4.3.0](https://cloudsmith.io/~opencpn/repos/autopilot-route-prod/packages/)
[Findit 1.2.14.0](https://github.com/rgleason/FindIt_pi) 
[Celestial Navigation  2.3.11.0](https://github.com/rgleason/celestial_navigation_pi) 
[AISradar 1.2.19.0](https://cloudsmith.io/~opencpn/repos/aisradar-prod/packages/)
Engine Dashboard FIXED 

**Not pushed to PIM**
AutoTrackRaymarine - configured for Win only

**Comment by bdbcat** [comment]
Tests on MacOS only, simple smoke test:  "Will it import, install,  and activate?"
WeatherRouting 1.13.35.0......OK
WeatherFax 0.7.15.0......OK
Watchdog 2.4.39.0......OK
Squiddio 1.3.15.0.......**NOT OK**
Pypilot 0.30.3.0.......OK
Polar 1.1.24.0........OK

Good Progress.  I will take a look at Squiddio tomorrow.
Dave

**Comment by rgleason** [comment]
Dave I may have lost the sound retrieval aspect of Weatherfax with this upgrade.(downgrade).
Checking the[ commit ](https://github.com/rgleason/weatherfax_pi/commit/0bc394602a378228d06a89435d8869f8093623f8) it appears that we have not changed anything that would affect retrieving sounds. However this needs to be tested at some point with a real weatherfax.

**Comment by rgleason** [comment]
Will push to PIM the OK

**Comment by rgleason** [comment]
Where was my head last night, I named wxfax 1.9.27.0  as 0.7.15.0. 
I am going to make a new commit with 1.9.28.0  as don't want to rewrite history. Sorry.

What do we do about the version numbers not changing in PIM for these plugins?
[DashboardTactics 1.6.10.0 ](https://cloudsmith.io/~opencpn/repos/dashboardtactics-beta/packages/)  
[Plots 2.2.10.0](https://cloudsmith.io/~opencpn/repos/plots-prod/packages/)
Something isn't right I think.

**Comment by rgleason** [comment]
Here is a list of MacOS plugins, along with list of plugins that have not been built for MacOS
https://www.cruisersforum.com/forums/f134/macos-pim-plugins-testing-258613.html#post3534640

NO MACOS VERSION AVAILABLE
AIS Radar View 1.2.17.0 Not Tested
Celestial Navigation 2.3.10.0 Not Tested
Findit 1.2.12.0 Not Tested
NmeaConverter 1.2.0.2 Not Tested
Photolayer 3.5.1 Not Tested
Radar 5.2.2 Not Tested
Race Start Display 1.1.0.0 Not Tested
sar 2.8.2.0 Not Tested
TwoCan Plugin 2.0.0.0 Not Tested
Tactics 1.0.24.0 Not Tested
VDR 1.3.12.0 Not Tested
vfKaps 2.1.1.7 (not present)
Windvane 1.0.22.0 Not Tested

We really should have a VDR_pi for MacOS.
