### ISSUE TITLE
autopilot_route linux failures

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#232]
Jon, Can you help me with these linux failures?  They've been around for awhile when I look back at the commits.
https://github.com/rgleason/autopilot_route_pi/commits/master
[autopilot-route-errorsnew 1.txt.docx](https://github.com/jongough/testplugin_pi/files/7688283/autopilot-route-errorsnew.1.txt.docx)

At lease macos and flatpak are building along with some others.../

**Comment by jongough** [comment]
You have two issues, the ternary is incorrectly formatted, you have:
```
        seta = tttg_sec > SECONDS_PER_DAY ?
            eta.Format(_T("%b %d %H:%M")) : eta.Format(_T("%H:%M"));
```
instead of:
```
        seta = (tttg_sec > SECONDS_PER_DAY) ?
            eta.Format(_T("%b %d %H:%M")) : eta.Format(_T("%H:%M"));
```
Note the missing '(' & ')' on the first line. Then you will need to use `-fPIC` during the build of nmea0183.

**Comment by rgleason** [comment]
Jon, I've enlarged it and don't see the "&". I think github swallowed it!
Can you show me where it is supposed to be?

I will try making those change.  Thanks!

**Comment by jongough** [comment]
The `(` and the `)` are missing on the first line

**Comment by rgleason** [comment]
I' ve got it, now missing ( and ) on first line.

**Comment by jongough** [comment]
In OD for nmea0183 to get the `-fPIC` I add `set(CMAKE_POSITION_INDEPENDENT_CODE ON)` to the CMakeLists.txt file.

**Comment by rgleason** [comment]
Oh. Ok.  After the   after the closing set(SRC   ) bracket,  I added "ADD_DEFINITIONS( " -fPIC")"

I will replace this with set(CMAKE_POSITION_INDEPENDENT_CODE ON)

**Comment by rgleason** [comment]
We will see how it does https://github.com/rgleason/autopilot_route_pi

**Comment by rgleason** [comment]
Looking good!  Awesome.

**Comment by rgleason** [comment]
Line 794 
```
double autopilot_route_pi::FindXTE()
{
    // find a position along this bearing
    double dlat, dlon, brg, xte;
    PositionBearing(m_current_wp.lat, m_current_wp.lon, m_current_wp.arrival_bearing, 1, &dlat, &dlon);
    wp b(m_lastfix.Lat, m_lastfix.Lon), w(dlat, dlon);
    wp p = Closest(b, m_current_wp, w);
    DistanceBearing(m_lastfix.Lat, m_lastfix.Lon, p.lat, p.lon, &brg, &xte);
    if(isnan(xte))     <-------------------------LINE 794
        xte = 0;
    else if(heading_resolve(brg - m_current_wp.arrival_bearing) < 0)
        xte = -xte;
    return xte;
}    

```

**Comment by jongough** [comment]
In other plugins I have changed `isnan` to `wxIsNaN` and this solved the issue.

**Comment by rgleason** [comment]
So at the top of the file  autopilot_route_pi.cpp:794:17

# define std:isnan(x)

and at Line 794 change to ?
if(wxnan(xte))

**Comment by jongough** [comment]
Nope, change `isnan` to `wxIsNaN`.

**Comment by rgleason** [comment]
Ok, will do. Thanks

**Comment by rgleason** [comment]
That fixed xenial!  Thank you.
