### ISSUE TITLE
Raspbian Fixes

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#234]
Jon, What do you think of this Issue posted by Mike G.
https://github.com/OpenCPN/OpenCPN/issues/2494#issuecomment-991266030

Lots of TP PI seem to be failing.

**Comment by jongough** [comment]
I have no way at the moment of testing Pi 3 or 4 software. I am trying to get a virtual Pi running, but not having much luck.

**Comment by rgleason** [comment]
I think it might have something to do with the way Opencpn builds for raspbian. Myvw we will find out eventually.
https://github.com/OpenCPN/OpenCPN/issues/2494
