### ISSUE TITLE
Update Linux and Flatpak plugins to use wxWidgets 3.1.5?

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#243]
Jon, does this commit also apply to testplugin?  (Has it been done, before I start updating?)  Sometimes it is hard to keep track of these changes....
https://github.com/OpenCPN/OpenCPN/pull/2506

**Comment by jongough** [comment]
I have no idea. The whole plugin process changes so randomly, with no consistency, and at the whim of the plugin manager it is impossible to keep up. Plugin manager is always out of date particularly with its xsd which is used to check the validity of updates. It makes changes impossible to manage.

**Comment by rgleason** [comment]
Sorry, Jon. I agree, it seems to be pretty endless. Perhaps we should just wait and see what happens before doing anything more? It wouldn't be the end of the world.

**Comment by rgleason** [comment]
Jon, Alec responded here
https://github.com/OpenCPN/OpenCPN/issues/2396#issuecomment-1020690861

It looks like your changes are good to use to update the TP plugins for awhile, because the linux/flatpak wxWidgets 3.1.5 update is really to confirm the next steps in the process.

Alex reviews a lot considerations (I know nothing about!) and it seems like the course to move forward is defined mostly by outside events and conditions. Unfortunately there is not much we can do except grumble sometimes. Thankfully this is not something I am involved in!

**Comment by rgleason** [comment]
PS. You can close this if you'd like.
