### ISSUE TITLE
Watchdog update to TP 1.0.193

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#247]
Everything built except android. It has worked in the past, however the libs/nmea0183 seems to be unable to find wx/string.h
Line 540
https://app.circleci.com/pipelines/github/rgleason/watchdog_pi/302/workflows/45b81992-093d-4a40-bbd0-3d9509e24120/jobs/3392

```
In file included from /home/circleci/project/libs/nmea0183/src/nmea0183.cpp[ 67%] Building CXX object libs/nmea0183/CMakeFiles/NMEA0183.dir/src/mwv.cpp.o
:33In file included from :
/home/circleci/project/libs/nmea0183/src/latlong.cpp/home/circleci/project/libs/nmea0183/src/nmea0183.h::3350:
:/home/circleci/project/libs/nmea0183/src/nmea0183.h10::50 :fatal error10: : fatal error: 'wx/string.h' file not found'wx/string.h' file not found

#include "wx/string.h"#include "wx/string.h"
```

         ^~~~~~~~~~~~~         ^~~~~~~~~~~~~

**Comment by rgleason** [comment]
libs/nmea0183/src/nmea0183.h 

Line 50

//    Include wxWindows stuff
//#include "wx/wxprec.h"      <<<----- SHOULD THIS BE UN COMMENTED?

//#ifndef  WX_PRECOMP
//  #include "wx/wx.h"
//#endif //precompiled headers
#include "wx/string.h"    <----LINE 50
#include "wx/list.h"
#include "wx/arrstr.h"

**Comment by jongough** [comment]
Can you check what OD does for this? I seem to remember that I only build the bits of NMEA that are needed and not the full lib.

**Comment by rgleason** [comment]
Giving up on this
