### ISSUE TITLE
Squiddio (now API 117) needs programming to allow control of Show/Hide waypoint text.

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#253]
Hide POI no longer works.
When I delete OD Points that works.

When I use Opencpn waypoints, Hide POI works.

**Comment by rgleason** [comment]
See https://github.com/mauroc/squiddio_pi/issues/141

"    1 .When "Show Text" is unchecked while using POI Option oDraw textpoint, text is not shown. However when you change to Opencpn Wpts option, the POI text is shown even when "Show Text" is unchecked.

Correct. This is a known issue, and it is due to the fact that before oDraw became available, there was no way to programmatically hide the text through the plugin API. Then oDdraw came about and it looked like a much more viable approach, so I have been encouraging users to select that rendering option. It would be my preference to eliminate POIs as Opencpn Wpts altogether, if it wasn't that oDraw is not always present. Alternative , I could make a PR to OCPN to introduce the option to hide text from wpts from within a plugin

**Comment by rgleason** [comment]
This is still an issue.  We need a change to the plugin API.

**Comment by antipole2** [comment]
````
// Extended Waypoint manipulation API
class DECL_EXP PlugIn_Waypoint_Ex {
public:
  PlugIn_Waypoint_Ex();
  PlugIn_Waypoint_Ex(double lat, double lon, const wxString &icon_ident,
                     const wxString &wp_name, const wxString &GUID = "",
                     const double ScaMin = 1e9, const bool bNameVisible = false,
                     const int nRanges = 0, const double RangeDistance = 1.0,
                     const wxColor RangeColor = wxColor(255, 0, 0));
  ~PlugIn_Waypoint_Ex();
  void InitDefaults();

  bool GetFSStatus();  // return "free standing" status
                       // To be a "free standing waypoint"(FSWP),
                       // the RoutePoint will have been created by GUI dropping
                       // a point; by importing a waypoint in a GPX file or by
                       // the AddSingleWaypoint API.

  int GetRouteMembershipCount();  // Return the number of routes to which this
                                  // WP belongs

  double m_lat;
  double m_lon;

  wxString m_GUID;

  wxString m_MarkName;
  wxString m_MarkDescription;
  wxDateTime m_CreateTime;
  bool IsVisible;                                 <---------------------- waypoint
  bool IsActive;

  double scamin;
  bool b_useScamin;
  bool IsNameVisible;                         <----------------------  mark name
  int nrange_rings;
  double RangeRingSpace;
  wxColour RangeRingColor;

  wxString IconName;
  wxString IconDescription;

  Plugin_HyperlinkList *m_HyperlinkList;
};
````

**Comment by rgleason** [comment]
Thank you Tony.  I will advise Mauro Calvi. Closing

It is in API 117, line 1487  or ocpn-plugin.h   dated 3/10/2023
  
```
// API 1.17
extern "C" DECL_EXP void ZeroXTE();

// Extended Waypoint manipulation API
class DECL_EXP PlugIn_Waypoint_Ex {
```

**Comment by rgleason** [comment]
Closed wrong thread. Opening.

**Comment by rgleason** [comment]
@mauroc  https://github.com/mauroc
We are going to be updating TP Template to 1.0.237 do you think you could make the necessary changes to show and hide POI and Show Text, before that?

**Comment by rgleason** [comment]
Mauro   We've updated your plugin Squiddio to use API version 117 now.  Do you think you can update squiddio to fix the text problem now? 

(I will be making a PR to your squiddio soon, once we have updated a few more things.) Thanks.

**Comment by rgleason** [comment]
Not completed but there is a similar Open Issue under Squiddio.
