### ISSUE TITLE
Debian 10 armhf: wrong gtk version.

### ISSUE THREAD

**Issue by leamas** [jongough/testplugin_pi#255]
As described in https://github.com/OpenCPN/OpenCPN/issues/2612#issuecomment-1099136521. The PPA ubuntu 18 build is linked against gtk2, but testplugin is linked against gtk3. This causes bad crashes when trying to load plugin.

**Comment by rgleason** [comment]
What the dickens? It would be nice if this business got settled. I don't really follow any of it, but every change causes "Yet another rebuild of all the XXXX plugins" (YARAxxxxPI). This cannot continue and will not.

**Comment by rgleason** [comment]
One bug and then another bug, then another bug.  It is all bugs.

**Comment by rgleason** [comment]
Well, I guess I will just remove all those bad builds for the time being.

**Comment by rgleason** [comment]
Please refer to  [TP Template: Scheduled and Unscheduled builds #256 ](https://github.com/jongough/testplugin_pi/issues/256)

**Comment by rgleason** [comment]
Before removing these xml I want to be sure I have the right ones. Is the correct one to remove:

celestial_navigation_pi-2.3.13.0-**ubuntu-armhf-18.04**.xml

**Comment by leamas** [comment]
At a closer look, this is about the Debian/10-armhf builds only. At a glance it looks like the Ubuntu/18-armhf builds are linked to gtk2 i. e., they are OK.

**Comment by rgleason** [comment]
@leamas  Thanks.  @jongough  Is this your understanding?  Thanks.

**Comment by rgleason** [comment]
Then the title should be changed to be accurate!

**Comment by leamas** [comment]
done

**Comment by rgleason** [comment]
Thanks

**Comment by jongough** [comment]
I have just pushed to github a change to build debian-armhf with gtk2. The files are all in cloudsmith opencpn/testplugin_pi-alpha and the version number is 1.0.196.0. and have created a pull request on plugins-alpha for testing.

**Comment by leamas** [comment]
@jongough: the Alpha looks good, works with my modified sloppy package, should work with the PPA as well (not tested).

Given that current master actually causes a hard error, please update master asap.

**Comment by jongough** [comment]
This part of a bigger fix trying to get OD to work reliably on msWindows, macOS and android armhf, so it needs some real user testing before it can/should be moved to prod. Not sure who can do this.

**Comment by leamas** [comment]
@jongough: Nor am I. However, just trying to install cuurent version makes OpenCPN crash, and after that it is not really possible to   restart again. So I suggest that you push the gtk3->gtk2 change here and now, and looks into further testing in next step..

An alternative is of course to just remove all testplugin-based Debian-10-armhf builds from the catalog for now. It's somewhat brutal, but a better option than providing plugins which breaks OpenCPN

**Comment by rgleason** [comment]
https://github.com/OpenCPN/plugins/pull/663

**Comment by rgleason** [comment]
The immediate issue should be resolved once bdbcat merges, and Jon has updated testplugin to 1.0.196 which fixes this, so I guess the issue can be closed, but the plugins aren't built. Won't be built for 3 months unless there is another OS wide bug found.

**Comment by jongough** [comment]
We need testing  to cover more of the platforms that are being built/used. It is currently possible to build for more platforms than developers have test environments for or time to do the testing. With the need to support multiple versions of gtk and wxWidgets as well as platforms that are almost impossible to debug on and others that seem to be making it impossible to build development environments that truly reflect the real device the need for real world testers using real hardware is now becoming a critical resource shortage.

**Comment by jongough** [comment]
Version 1.0.196.0 contains the change to build against gtk2 for debian armhf buster. This has been applied to alpha, beta and master branches

**Comment by leamas** [comment]
Closing.

> We need testing to cover more of the platforms that are being built/used. 

Indeed. In the sense "could be loaded" such tests would be  automated in a a better world. This means we need a scaled-down version of opencpn which can load plugins   and report results on the command line. I have some work in this direction, but it's huge and complicated and nothing which will take form before this summer, if ever.

**Comment by jongough** [comment]
Whilst at "could be loaded" would be useful it is more complicated with the different platforms/systems and implementations of events and clean-ups. For OD which has many events and timers it would appear that android with qt does things differently to ubuntu which is different to macOS (it looks like catalina is different to monterey (sp?)) which is different again to ms windows. All 'should' be the same with widgets, but.... This makes testing more complicated as startup, close-down, clean up, etc. have to be tested with dialogs open and timers running or the testing is not complete enough to see if it is compatible. With the number of environments now supported(?) it is difficult for any one person to be able to test all environments. Plugins, as they depend on the OCPN implements things makes it even more difficult as most developers only know one or two platforms.
