### ISSUE TITLE
TP Frontend2  - update?

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#261]
Jon 

We've been working on weatherfax and I would like to build and deploy to the Beta Catalog with as many OS as possible and ask plugin testers to try it out.
Should I use these files or not?

https://github.com/jongough/testplugin_pi/tree/updates

**Comment by jongough** [comment]
It should all work except for bionic-gtk3 which is colliding with bionic due to a package naming issue. I am working on it, but...
I think it is nearly ready, but testing is taking time.

**Comment by rgleason** [comment]
Thanks
