### ISSUE TITLE
Cleanup tinyxml - Is this something needed for TP?

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#274]
From OpenCPN development
https://github.com/OpenCPN/OpenCPN/pull/2786

https://github.com/leamas/OpenCPN/commit/d31d764de720c01153434c5800d3c0e47ee6e6b4

**Comment by rgleason** [comment]
No response. Closing.

**Comment by jongough** [comment]
Sorry, been busy trying to sort out an armhf issue on a Raspberry Pi3B+ where the wxWidgets work slightly differently. Not sure why.

I did look at tinyxml but I am not sure it is a problem that exists with testplugin. The changes that were made seem to already be in place. If you can see different can you please let me know?

**Comment by rgleason** [comment]
Ok. Thanks.
