### ISSUE TITLE
New plugin ABIs for 5.8.0

### ISSUE THREAD

**Issue by leamas** [jongough/testplugin_pi#275]
The upcoming 5.8.0 version will use a different set of ABIs compared to current status. This is partly because of using wxWidgets 3.2 and partly due to the "use debian plugins on ubuntu [roadmap](https://github.com/OpenCPN/OpenCPN/discussions/2502#discussioncomment-1904180)"

The set of plugins to use is described in the top comment of https://github.com/OpenCPN/OpenCPN/discussions/2797. Since this affects all plugins build chains, please keep discussions on what to build in that discussion.

**Comment by leamas** [comment]
As of now, parts of this is blocked on https://github.com/OpenCPN/plugins/pull/747

**Comment by rgleason** [comment]
Jon, I don't know if you've been following this.
https://github.com/OpenCPN/OpenCPN/discussions/2797#discussioncomment-4177148

**Comment by jongough** [comment]
I have, but not getting involved. 

- We don't have enough testers for the current environments so plugins are released that have issues that should have been found, this is just going to exacerbate this. 
- There are only so many builds that can be done before circleci stops allowing them, the more versions being built the thinner these are spread.
- The xml process is still being used in a convoluted way using build environment names contained within a single element, and in an inconsistent way, making the build scripts more complex. This is getting more and more complex and convoluted.
- ABI is for binary interfaces not dependencies. OD uses this to handle an ABI change in the gcc compiler from 0 (none) to 3 (GNU). OCPN uses 0, so OD has to change to this to allow the plugin library to be loaded.
- There is too much churn in the whole process so I will wait until it is settled and then update FE2 to handle it.

**Comment by rgleason** [comment]
Ok, understood. Here's another post for later reference.
https://github.com/OpenCPN/plugins/pull/749#event-7850514496

**Comment by rgleason** [comment]
Thank you Alec, I think this can be closed now. Thanks for closing.

**Comment by leamas** [comment]
This is Jon's show, he is the one to state that this issue/update  is completed

**Comment by rgleason** [comment]
You know Jon, I think this is done now, so please close it If you agree.

**Comment by jongough** [comment]
Updated to create required xml tuples and file names
