### ISSUE TITLE
weatherfax flatpak does not compile

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#276]
Jon, I am trying to build an updated version of weatherfax before having to embark on a whole new set of builds using wx32 and the flatpak version seems to fail with this result.  Can you advise how I can get it building and completing?  I believe I have updated to latest testplugin version.

https://github.com/rgleason/weatherfax_pi

https://app.circleci.com/pipelines/github/rgleason/weatherfax_pi/322/workflows/7186c7b8-c6b2-48ae-940e-0aee744495b7/jobs/4263

```
Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/circleci/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

+ '[' stable = beta ']'
+ flatpak install --user -y flathub org.freedesktop.Sdk//20.08
error: Nothing matches org.freedesktop.Sdk in remote flathub

```

**Comment by rgleason** [comment]
Yes,that is what the Commit shows,  but weatherfax uses curl I think to fix the download of some website weatherfaxes, and bdbcat added some libs in extra directory, which perhaps conflict with FE2 1.0.215?

See 
https://github.com/rgleason/weatherfax_pi/tree/master/ci/extras

https://github.com/rgleason/weatherfax_pi/blob/master/ci/extras/circleci-build-flatpak_extra_libs.txt

https://github.com/rgleason/weatherfax_pi/blob/master/ci/extras/circleci-build-android-arm64_extra_libs.txt

**Comment by rgleason** [comment]
I found that there was a difference between the circleci-build-flatpak.bak and  circleci-build-flatpak.sh  and so added these lines 31-44

```
# Install extra build libs
ME=$(echo ${0##*/} | sed 's/\.sh//g')
EXTRA_LIBS=./ci/extras/extra_libs.txt
if test -f "$EXTRA_LIBS"; then
    while read line; do
        sudo apt-get install $line
    done < $EXTRA_LIBS
fi
EXTRA_LIBS=./ci/extras/${ME}_extra_libs.txt
if test -f "$EXTRA_LIBS"; then
    while read line; do
        sudo apt-get install $line
    done < $EXTRA_LIBS
fi
```

**Comment by rgleason** [comment]
After making this change and pushing,  circleci-build-flatpak.sh still does not build!!

See  https://app.circleci.com/pipelines/github/rgleason/weatherfax_pi/323/workflows/4618b451-b413-4be9-9638-fbc26ef19503/jobs/4271

```
Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/circleci/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

+ '[' stable = beta ']'
+ flatpak install --user -y flathub org.freedesktop.Sdk//20.08
error: Nothing matches org.freedesktop.Sdk in remote flathub

```

If you can figure this problem out it would be good, otherwise I am going to have to bother bdbcat who is very busy right now.

**Comment by jongough** [comment]
I have added back in the missing 'extras' that happened on the last update when doing flatpak changes. I have created a pull request for my update to weather_fax which seems to build OK for flatpak_arm64. The android_arm(64/hf) fail.
