### ISSUE TITLE
Ocpn_Draw for 5.7.1  seems to be missing for Windows

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#281]
I don't find Ocpn-Draw for windows. Wanted to give it a try.

```
C:\Users\fcgle\AppData\Local\opencpn\plugins\o-charts_pi.dll
15:09:20.902 MESSAGE plugin_loader.cpp:255 Checking plugin candidate: C:\Users\fcgle\AppData\Local\opencpn\plugins\ocpn_draw_pi.dll
15:09:20.903 MESSAGE plugin_loader.cpp:1151 Plugin is compatible: false
15:09:20.903 MESSAGE plugin_loader.cpp:311 Incompatible plugin detected C:\Users\fcgle\AppData\Local\opencpn\plugins\ocpn_draw_pi.dll
15:09:20.903   ERROR filefn.cpp:905 Failed to copy the file 'ocpn_draw_pi.dll' to 'ocpn_draw_pi.dll.jail' (error 2: The system cannot find the file specified.)
15:09:20.903   ERROR filefn.cpp:1029 File 'ocpn_draw_pi.dll' couldn't be renamed 'ocpn_draw_pi.dll.jail' (error 2: The system cannot find the file specified.)
15:09:20.903 MESSAGE plugin_loader.cpp:314 Jailing: ocpn_draw_pi.dll
15:09:20.903 MESSAGE plugin_loader.cpp:255 Checking plugin candidate: C:\Users
```\fcgle\AppData\Local\opencpn\plugins\otcurrent_pi.dll

**Comment by jongough** [comment]
There should be a beta version in the OCPN catalog with the changes needed to make the icons in the OD toolbar.

**Comment by rgleason** [comment]
Jon,  This is a big improvement we can see the icons!
Would it be possible to have an icon adjustment bar in the General Tab under preferences?

![Screenshot (445)](https://user-images.githubusercontent.com/2363959/212498515-0e2af71c-a6f4-49a6-9000-58a87010bb52.png)

![Screenshot (444)](https://user-images.githubusercontent.com/2363959/212498523-e75f0819-afe0-40b1-b97e-82822e4464cf.png)

Another pesky thing is the way text is displayed in a huge yellow box and the text is really pretty bad.  How can that be improved?

**Comment by jongough** [comment]
I raised this issue in the OCPN issue around wxwidgets and changes introduced for OCPN 5.7.1, but Dave did not want me to continue to use defaults and didn't like the idea of it. So this is what you have. I also cannot get around to addressing this issue for at least 3 weeks. I think there needs to be a rationalisation of the changes that are being implemented. It has taken me over 2 weeks just to get a debugging version of OCPN and OD running on a windows vm as multiple build and environment issues had to be solved. There are still serious issues around opengl, wxwidgets, vs2022, documentation, etc.

**Comment by rgleason** [comment]
Ok. Sorry about this Jon.
