### ISSUE TITLE
Compare testplugin rgleason to jongough 

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#288]
https://github.com/jongough/testplugin_pi/runs/10651681404

Compared to https://github.com/jongough/testplugin_pi/issues/284

    build-android-arm64 - Success
    build-android-armhf - Success

    build-macos - Success
    build-macos-wx32 - Success
	
	msvc-x86
	msvc-x86-wx32

    build-armhf-ubuntu-buster - Success	
    build-armhf-ubuntu-focal - Success
    build-buster - Success
    build-bionic - Success
    build-bionic-gtk3 - Success	
    build-focal-gtk3 - Success		

    build-jammy - Success

    build-armhf-debian-buster - Success	
    build-armhf-debian-buster-gtk3 - Success
    build-armhf-debian-bullseye - Success
    build-arm64-debian-bullseye - Success	
	      x86-debian-buster   <<-------------------missing

    build-armhf-stretch - Success   <<------------remove

	build-flatpak-arm64 - Success
    build-flatpak-x86-1808 - Success
    build-flatpak-x86-2008 - Success
    flatpak-x86_64 	flatpak-aarch64-20.08 	20.08 fltpk <---- missing		
	flatpak-x86_64 	flatpak-x86_64-22.08 	22.08 fltpk <----  missing
	flatpak-aarch64 flatpak-aarch64-22.08 	22.08 fltpk <----  missing
    flatpak-arm64 	flatpak-arm64-22.08 	22.08 fltpk <----  missing
 

also compare to https://www.cruisersforum.com/forums/f134/opencpn-beta-version-5-7-1-beta-test-1-plugins-271525.html#post3745111

Testplugin_pi 1.0.226 TESTING

o580 (&5.7.1) darwin-wx32-x86_64-11.4-macos.xml <--Tested bcn
o562 darwin-x86_64-11.4-macos.xml <--Tested Previously

o562 msvc-x86_64-10.0.14393-MSVC.xml <-- Tested previously
o580 msvc-x86_64-wx32-10.0.17763-MSVC.xml <-- Tested Many

o580 debian-arm64-10-buster-arm64.xml
o580 debian-arm64-11-bullseye-arm64.xml <---Tested bdbcat
o580 debian-armhf-10-buster-armhf.xml
o580 debian-armhf-10-gtk3-buster-armhf.xml
o580 debian-armhf-11-bullseye-armhf.xml <-- Tested Duichan
o580 debian-x86_64-10-buster.xml <-- Tested bdbcat
o580 debian-x86_64-11-bullseye.xml <-- Tested bdbcat

o580 flatpak-aarch64-20.08-flatpak-arm64.xml <--- Tested HUR450502
o580 flatpak-x86_64-20.08-flatpak.xml
o580 flatpak-x86_64-22.08-flatpak.xml <-- Tested bdbcat

o562 ubuntu-armhf-18.04-buster-armhf.xml <-- Old & Probably working
o562 ubuntu-armhf-20.04-gtk3-focal-armhf.xml <-- Old & Probably working
o562 ubuntu-x86_64-18.04-bionic.xml <--Old & Probably working
o562 ubuntu-x86_64-18.04-gtk3-bionic-gtk3.xml <-- Old & Probably working
o562 ubuntu-x86_64-20.04-gtk3-focal-gtk3.xml <-- Tested Lennart
o580 ubuntu-x86_64-22.04-jammy.xml <-- Tested Ozolli

o562 raspbian-armhf-9.13-stretch-armhf.xml <-- Old & Probably working

https://github.com/rgleason/testplugin_pi

**Comment by rgleason** [comment]
Compare filename output to cloudsmith

1.0226
android-arm64-16-android-arm64.xml            
android-armhf-16-android-armhf.xml
darwin-wx32-x86_64-11.4-macos.xml
darwin-x86_64-11.4-macos.xml
debian-arm64-10-buster-arm64.xml
debian-arm64-11-bullseye-arm64.xml
debian-armhf-10-buster-armhf.xml
debian-armhf-10-gtk3-buster-armhf.xml
debian-armhf-11-bullseye-armhf.xml
debian-x86_64-10-buster.xml
debian-x86_64-11-bullseye.xml
flatpak-aarch64-20.08-flatpak-arm64.xml
flatpak-x86_64-22.08-flatpak.xml
msvc-x86_64-10.0.14393-MSVC.xml
msvc-x86_64-wx32-10.0.17763-MSVC.xml
ubuntu-armhf-18.04-buster-armhf.xml
ubuntu-armhf-20.04-gtk3-focal-armhf.xml
ubuntu-x86_64-18.04-bionic.xml
ubuntu-x86_64-18.04-gtk3-bionic-gtk3.xml
ubuntu-x86_64-20.04-gtk3-focal-gtk3.xml
ubuntu-x86_64-22.04-jammy.xml


1.0.227
android-arm64-16-android-arm64.xml
android-armhf-16-android-armhf.xml
darwin-wx32-x86_64-11.4-macos.xml
darwin-x86_64-11.4-macos.xml
debian-arm64-10-buster-arm64.xml
debian-arm64-11-bullseye-arm64.xml
debian-armhf-10-buster-armhf.xml
debian-armhf-10-gtk3-buster-armhf.xml
debian-armhf-11-bullseye-armhf.xml
debian-x86_64-10-buster.xml
debian-x86_64-11-bullseye.xml
flatpak-aarch64-20.08-flatpak-arm64.xml
flatpak-x86_64-20.08-flatpak.xml
msvc-x86_64-10.0.14393-MSVC.xml
msvc-x86_64-wx32-10.0.17763-MSVC.xml
**raspbian-armhf-9.13-stretch-armhf.xml    <--- No**
**Need  ----> ubuntu-armhf-18.04-buster-armhf.xml**
ubuntu-armhf-20.04-gtk3-focal-armhf.xml
ubuntu-x86_64-18.04-bionic.xml
ubuntu-x86_64-18.04-gtk3-bionic-gtk3.xml
ubuntu-x86_64-20.04-gtk3-focal-gtk3.xml
ubuntu-x86_64-22.04-jammy.xml

**Comment by jongough** [comment]
Is this a problem? The new OCPN has not been released yet so we still need to build and provide the older versions. As far as I can see testplugin is building for all the required environments and a couple(?) of current production environments.

**Comment by rgleason** [comment]
Build for o56 is Ok.

Leaving raspbian-armhf-9.13-stretch-armhf.xml  is okay but they should be using flatpak I believe, that is why bdbcat had me remove it, because it is retired.

However we do need " ubuntu-armhf-18.04-buster-armhf.xml"

**Comment by rgleason** [comment]
I think we should test 1.0.227 in the Beta catalog once we make those minor fixes.

**Comment by rgleason** [comment]
I've created a PR for 1.0.227 to plugins Beta Catalog
https://github.com/OpenCPN/plugins/pull/825

**Comment by jongough** [comment]
I have just merged my updates with master. So it should now appear in the Beta catalog when the build finishes and I push the requisite xml.

**Comment by rgleason** [comment]
Any changes? .. as I've pushed it to the Beta Catalog.   I could push it again...

**Comment by jongough** [comment]
No changes. I have just created a new release for 1.0.227.0 which will create the files in the prod repository. Should make it easier for testers, but....

**Comment by rgleason** [comment]
Closing. Resolved and done.
