### ISSUE TITLE
TP-Appveyor download proposal

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#293]
https://github.com/OpenCPN/OpenCPN/discussions/3096

**Comment by jongough** [comment]
This is already handled by CMakeLists.txt where the repository and user is set in lines 62 & 64. The developer can then change where the uploads goto, lines 56, 57 & 58 give the names of the repositories . Not really sure what is missing.

**Comment by rgleason** [comment]
nothing is missing. closing
