### ISSUE TITLE
Failing to compile locally

### ISSUE THREAD

**Issue by LennartG-Sve** [jongough/testplugin_pi#297]
Long time using Ubuntu 20.04 and now also a fresh install of xubuntu 20,04. Both systems have libgtk-3-dev as well as wxwidgets 3.0 with headers, libraries and dev additions installed. Also linked with 'cd /usr/include' followed by 'sudo ln -sv wx-3.0/wx wx'  

Kept the GPS Odometer FE2 functionality on track using a limited selection from TP libraries/files: .circleci/, ci/, cmake/, libs/ocpn-api/, mingw/ and appveyor.yml plus updates in CMakeList.txt.
This worked fine up to TP ver 194. Next try using TP 212 failed although upload to git worked and is currently in prod for several platforms.

Decided to give TP/FE2 another try for 5.7.1 using the latest TP ver 240. Updated following the, slightly outdated, document 'Testplugin-CI-Cmake-v1.0.160.txt' and also updated to API 117 for socketCAN (should be in TP for those using it as FE2 framework).

The compile fails with:
-- PluginConfigure: wxWidgets_Version: 
-- PluginConfigure: wxWidgets components: base;core;net;xml;html;adv;aui
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS)

This, VX_VER found empty, is the same error I've got since TP v212, meaning wxWidgets not found. A second issue is that the compile also uses gtk2 even though gtk3 is installed. Really looks like if cmake 'find_package' is not working. So: Are there any special parameters required when compiling or something else in error? Currently compiling the GPS Odometer plugin using these basic steps:

mkdir build 
cd build
cmake ..
cmake --build . --config release

Any ideas?

**Comment by jongough** [comment]
I know the documentation file in the root directory is out of date, but I was focused on getting automated builds to work. This means if you want to build locally you will need to look at the circleci/appveyor build files and the associated build scripts to see what is set to allow the build.

With the change to wxWidgets 3.2 a rationalisation of this part was needed. So wx_ver can be set to 3.0 or 3.2, I think I removed the other wx* variables in the last commit/tag in the master branch. Rick may be able to advise as currently I am away.

**Comment by rgleason** [comment]
I think this is the commit where Jon changed the way  wx_ver worked. I think you'll get the idea.
https://github.com/jongough/testplugin_pi/commit/3b7319e669e4a05bb2fffd7566b4e8f727a85c0d

**Comment by rgleason** [comment]
I updated Lennarts PI to 1.0.230 and was able to build for Windows successfully, so I pushed those changes to him with some notes

https://github.com/LennartG-Sve/GPS-Odometer_pi/pull/17

**Comment by LennartG-Sve** [comment]
Thanks Jon and Rick, I'm sure I can manage from here.
Closing this one.

**Comment by LennartG-Sve** [comment]
Reopening this to add useful information for others compiling locally and to be documented:
Local compile requires that attributes are added to 'cmake ..'., the attributes are found in the circleci/appveyor build files, as mentioned by Jon above.
For ununtu 20.04 the cmake command could e.g. read:
 'cmake .. -DWX_VER=30 -DBUILD_GTK3=true':

**Comment by rgleason** [comment]
Thanks Lennart,   also covered here  https://github.com/jongough/testplugin_pi/issues/294#issuecomment-1484119444

**Comment by LennartG-Sve** [comment]
No recent comments, closing.
