### ISSUE TITLE
Unable to parse yaml in TP 1.0.232

### ISSUE THREAD

**Issue by LennartG-Sve** [jongough/testplugin_pi#302]
Tried twice to upload to git after updating to TP 1.0.232 and are getting this from .circleci/config.yml. see next comment for a screencut.

Looks simple enough but my eyes, or brain, is betraying me ;-)

**Comment by LennartG-Sve** [comment]
![bild](https://user-images.githubusercontent.com/71273808/233946328-65e8d5ad-cb1b-48e3-9e33-690c411cdb21.png)

Could not paste the text properly, see the picture.

**Comment by LennartG-Sve** [comment]
Rick,
   that was it! There were several spaces missing in the line 38-onwards section, note that this is the original file from TP, not edited in any way. 

The compile then gave those errors:

For 'build-bookworm':

_Error response from daemon: manifest for circleci/buildpack-deps:bookworm-scm not found: manifest unknown: manifest unknown_

and this for 'build-arm64-debian-buster':

_+ docker exec -ti /bin/bash -xec 'bash -xe ci-source/build.sh; rm -rf ci-source/build; mkdir ci-source/build; cd ci-source/build; cmake ..; make -j2; make package; chmod -R a+rw ../build;'
Error: No such container: /bin/bash
+ echo Stopping
Stopping_

Did a 'Rerun on failed' and they both failed again. All the others were ok, including jammy. I have though not tested the tar.gz packages yet. That is for tomorrow.

Leaving this open until tomorrow due to the compile errors unless advised otherwise.

**Comment by LennartG-Sve** [comment]
Rick et all,
got a few minutes and tested the tarballs for GPS-Odometer 7.02 from Cloudsmith beta:

1/ Ubuntu 20.04 (focal) installed and worked ok
2/Ubuntu 22.05 (jammy) gives the message (Incompatible import plugin detected).

**Comment by rgleason** [comment]
It should work, but I'd very much like to switch over to using debian builds.
What happens with other plugins?

**Comment by jongough** [comment]
As far as I can tell the builds are actually ubuntu builds built on ubuntu images (circleci does not support images built on debian) so for a true debian build a docker image would need to be created. Shipdriver seems to be using ubuntu machines so I am not really sure what makes them debian builds.

**Comment by rgleason** [comment]
Jon, I am confused, how are the current debian being built? I see debian in the circleci config.yml?

Perhaps @bdbcat can shed some light on how to proceed so that this does not need to be a long road!

**Comment by bdbcat** [comment]
Here is a build of shipdriver, using a  CCI debian/Bullseye docker image, AFICT:
https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/912/workflows/1b332e1d-3750-4172-a425-33668b0a8da9/jobs/8090

It may be that there is no CCI image for bookworm yet, in which case I think shipdriver is using ubuntu 22.04 as a substitute.

Not sure how this relates to Lennart's question.

**Comment by jongough** [comment]
As far as I can see it is using a ubuntu environment:
```
Build-agent version 1.0.167442-c2c298be (2023-04-14T17:51:19+0000)
System information:
 Server Version: 20.10.18
 Storage Driver: overlay2
  Backing Filesystem: xfs
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Kernel Version: 5.15.0-1030-aws
 Operating System: Ubuntu 20.04.5 LTS
 OSType: linux
 Architecture: x86_64
```
based on the `config.yml` this entry appears to be ubuntu:
```
  build-bookworm:
    machine:
      image: ubuntu-2004:2022.04.1
    resource_class: medium
    environment:
      - OCPN_TARGET: bookworm
      - TARGET_TUPLE: debian;12;x86_64
      - CMAKE_BUILD_PARALLEL_LEVEL: 2
    steps:
      - checkout
      - run: ci/circleci-build-debian-docker.sh
      - run: cd build-debian; /bin/bash < upload.sh
      - run: ci/git-push.sh build-debian
```

This is not an debian environment. The code in shipdriver is pure ubuntu as circleci does not support debian any more just ubuntu. So now a docker image inside a ubuntu machine is needed. So why are we doing this? The whole thing is more complicated?

**Comment by LennartG-Sve** [comment]
@bdbcat , I consider the original issue solved so this one should either be closed or renamed to something like 'Ubuntu / Debian build structure'. The three build problems I found are also more a part of that discussion.
I was not aware of yaml pickiness or I would have solved it myself, sorry.

**Comment by jongough** [comment]
I have cobbled together a bookworm build using ubuntu with a debian docker and created, I think, a module that could be used. It is currently in the testplugin-alpha repository. I need to clean up the build scripts a bit, but I hope this may work. Can anyone try it out?

**Comment by rgleason** [comment]
Maybe we should ask on the forum?  It appears to be going to[ cloudsmith testplugin-alpha](https://app.circleci.com/pipelines/github/jongough/testplugin_pi/1337/workflows/1cb90961-1102-42b5-8e2f-0d2a43f882dc/jobs/10631)

So doing a search in [cloudsmith testplugin-alpha  using "1.0.232 wx32 debian bookworm"
](https://cloudsmith.io/~opencpn/repos/testplugin-alpha/packages/?q=1.0.232+wx32+debian+bookworm)
I guess the most recent should be used?   I will post this request in the forum.

**Comment by rgleason** [comment]
Posted  https://www.cruisersforum.com/forums/f134/tp-template-testing-needed-275176.html#post3770389

**Comment by bdbcat** [comment]
Lennart...
As the OP, please close this issue if you are satisfied with the resolution.
Rick/Jon...
Please start another issue if desired related to debian plugin CI build environment.

**Comment by rgleason** [comment]
New issue  https://github.com/jongough/testplugin_pi/issues/303

**Comment by LennartG-Sve** [comment]
Closing as the referenced issue is solved.
