### ISSUE TITLE
Difficult to debug incompatible plugin rejection or fault from normal logfile.

### ISSUE THREAD

**Issue by bdbcat** [jongough/testplugin_pi#305]
Improved logging of all relevant messages to standard logfile target will help debug

**Comment by jongough** [comment]
Testpluin does log all messages it knows about to the log. For developers there is additional logging to the debug window of the IDE being used.

Can you point to any messages that seem to be missing?

**Comment by bdbcat** [comment]
Jon...
Testplugin does a good job of logging its startup, better than most.
My issue is in OCPN core 5.8.0.  If there is a fault (crash) loading a particular plugin, often the last few log messages have not been flushed to disk, so are lost.  I plan to add more wxLog::FlushActive(); calls, to be sure and get all available info on a fault.  Not so much focused on developers, as on responding to user error reports.

**Comment by bdbcat** [comment]
Added more logging and strategic log flushing.
