### ISSUE TITLE
Possible? Change dependency for wxWidgets language files. Closes #3164 

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#308]
Does this need to happen with plugins?  
What code is needed?
https://github.com/OpenCPN/OpenCPN/pull/3165

**Comment by rgleason** [comment]
Maybe this is too complex for plugins?

**Comment by jongough** [comment]
Only one line seemed to need to be changed in the PluginSetup.cmake file to replace the wx3.0-I18n with wx-I18n
