### ISSUE TITLE
Upload: Some possible improvements

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#31]
[Revise metadata template file](https://github.com/bdbcat/oesenc_pi/commit/fd5bf333daef4256ce9b41b7aad338feb3a26a54)   -Needs to be done.

[ci: Add CMAKE_INSTALL_PREFIX to debian builds. ](https://github.com/bdbcat/oesenc_pi/commit/fd5bf333daef4256ce9b41b7aad338feb3a26a54)

[modified: cmake/PluginPackage.cmake ](https://github.com/bdbcat/oesenc_pi/commit/e0a31d4c5a018429e93d4e0c092d2d3f4733215e)

[Update to oserverd for OSX](https://github.com/bdbcat/oesenc_pi/commit/0be60fb441ec2bbfd72caa9619b4e0555c269a4a)  -don't really know about this. Just noticed it.

[ci: Upload: Reset tarball name to include version](https://github.com/bdbcat/oesenc_pi/commit/7716d633f712f382be8a9fe71bcc030577e9e8b3)   Note the ci/circleci-upload.sh changes for cloudsmith-upload.sh.in    Also they are working on naming.  Restore the tarball filename to match the spec at https://github.com/leamas/opencpn/wiki/Tarballs#tarball-names.
In particular, include the version in the generated filename.

[ci: Restore name of tarball. ](https://github.com/bdbcat/oesenc_pi/commit/e07b696fdf6ac5fd2d8d2c9faf186d773a75a73f)   Also affects cloudsmith-upload.sh.in

[ci:appveyor-upload: Simplify and streamline value.](https://github.com/bdbcat/oesenc_pi/commit/951fdcef46e72f4e98596a11ba2a6a6713fe25de)   Also simplifies the awkward code.

[build: Drop release part of version.](https://github.com/bdbcat/oesenc_pi/commit/ba8e6586eae90e4f9f51ed39d2d29e753bbb607e)   This should also probably be done for consistency.

He also removed an unused value in CMakeLists.txt but I don't know if this affects it. 
SET(PLUGIN_SOURCE_DIR .)

I guess I am going to have to do this with frontend 1 too.

**Comment by jongough** [comment]
For what is happening now the naming is not rich enough to catch what is needed. We need to know all the following bits of information:
Plugin name
Plugin version
OCPN version it is meant for
Build environment (particularly important for mingw and msvc)
Platform installable on
Platform version
Platform version name

This is what the current naming does. The issue was brought to a head when using Linux Mint which reports differently to standard Ubuntu. So version numbers and names were required. From my testing the above does currently work, so I am concerned about changing the names again without the co-requisite documentation and changes for the PI Manager.

**Comment by jongough** [comment]
I have just pushed patch 1.0.50 which fixes up the names, I had missed renaming a variable in the upload script so the file name for cloudsmith was incorrect.

**Comment by jongough** [comment]
The link to the revised metadata template seems to be pointing me at compile options. Can you let me have the new template location?

When is this stuff going to be stable? I thought we were in 'beta' and these changes seem to be 'alpha' level changes. Can we get things like the XML sorted out and stabilised, the naming standards stabilised, etc. It is just 'make work' when trying to keep up.

**Comment by rgleason** [comment]
Jon I had the wrong link to the template file for revision of the name  sorry.
https://github.com/bdbcat/oesenc_pi/commit/5146d20edd280c1ab1eeb33cd51337f857233eef

These all came from the string of changes to oesenc that were made.  I just wanted to bring them to your attention. It's your judgement to make the change or not.

There is one other issue that needs to be fixed that I know of right now. The flatpak name of the file does not seem to match the  target-url and I have had to change that for mauro's squiddio and for weather_fax.   I don't know if that has been fixed in testplugin, but the frontend came from testplugin.

**Comment by jongough** [comment]
As of testplugin_pi 1.0.50.3 it should work. I have checked the flatpak name and it matches what is in the XML. This is in the master branch.

**Comment by rgleason** [comment]
What did you decide about those changes listed from oesenc?

**Comment by jongough** [comment]
I have implemented:
install prefix
arm64
PLUGIN_SOURCE_DIR

the other changes are either not relevant or equivalents have been done already

**Comment by rgleason** [comment]
Ok. Thanks. Closing
