### ISSUE TITLE
TP 1.0.237 does not build all supported OS

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#312]
It appears that we are missing the following metadata, from each plugin built with TP 1.0.237 Template.  Many users are reporting that TP Plugins are missing and there is a study done that shows the certain OS are missing.

From the [TP Template Table](https://github.com/jongough/testplugin_pi/issues/284)
For example [Climatology_pi 1.5.5 + TP1.0.237](https://github.com/rgleason/climatology_pi) was recently built and resulted in this list of metadata:

[climatology-metadata-result-list.txt](https://github.com/jongough/testplugin_pi/files/11564838/climatology-metadata-result-list.txt)

Flatpak |   |   |  
-- | -- | -- | --
flatpak-aarch64-22.08-arm64 | 22.08 fltpk | wx32 gtk3 | O58 Primary ADD  <---  DOES NOT EXIST
flatpak-x86_64-22.08 | 22.08 fltpk | wx32 gtk3 | O58 Primary ADD  <---- DOES EXIST

Debian 12 Bookworm |   | wx32 is assumed |  
-- | -- | -- | --
debian-arm64-12-bookworm | Jammy* | wx32 gtk3 | O58 ADD  <-- DOES EXIST - is the target correct?
debian-armhf-12-bookworm | Jammy* | wx32 gtk3 | O58 ADD  <-- DOES EXIST - is the target correct?
debian-x86_64-12-bookworm | Jammy* | wx32 gtk3 | O58 ADD  <---DOES EXIST - is the target correct?

### More Detail  

Filename (can be anything as it is not used)  |  Target (most important)  |

climatology_pi-1.5.5.0-debian-arm64-wx32-12-bookworm-arm64.xml  uses
  `<target>debian-wx32-arm64</target> `
climatology_pi-1.5.5.0-debian-arm64-wx32-12-bookworm-arm64.xml  uses 
  `<target>debian-wx32-armhf</target>`
climatology_pi-1.5.5.0-debian-x86_64-12-bookworm.xml    uses 
 `<target>debian-wx32-x86_64</target>`

All three seem to have a "-wx32" in the target. **_Is this correct?_**

Also Is it possible to make the last filename have -wx32 ?  Like this?

climatology_pi-1.5.5.0-debian-wx32-x86_64-12-bookworm.xml 

so that it is easy to determine which files are for O5.6.2 and O5.8.2?

**Comment by rgleason** [comment]
Additional Information:
Radar_pi 5.5.0  a Shipdriver Template has for Debian 12 Bookworm (arm64, armhf, x86_64)
  <target>debian-arm64</target>
  <target>debian-armhf</target>
  <target>debian-x86_64</target>

**Comment by rgleason** [comment]
Also see https://github.com/OpenCPN/OpenCPN/discussions/2986#discussioncomment-5986644
[aarch64: Debian package: No explanation to missing plugins.
#2986](https://github.com/OpenCPN/OpenCPN/discussions/2986#discussioncomment-5986644)

**Comment by rgleason** [comment]
Trying to figure out how to build   flatpak-aarch64-22.08-arm64
how does arm64 get built? where is the parameter for that?

In circleci/config.yml 
add after   " build-flatpak-x86-2208:"

    build-flatpak-arm64-2208:
        machine:
            image: ubuntu-2004:202010-01
        environment:
        - OCPN_TARGET:  flatpak
        - FLATPAK_BRANCH: beta
        - CLOUDSMITH_PKG_EXT: gz
        - SDK_VER: 22.08
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run:
            command: bash ci/circleci-build-flatpak.sh
            no_output_timeout: 30m
        - deploy-code

and at the top of config.yml add

        - build-flatpak-arm64-2208:
            <<: *std-filters

**Comment by rgleason** [comment]
From [Shipdriver v3.2.3 Cloudsmith shipdriver-prod](https://cloudsmith.io/~opencpn/repos/shipdriver-prod/packages/?q=3.2.3+metadata)

I think we can use these for the results that we need in TP Template.

**ShipDriver-sd3.2.3-debian-12.xml**
```
  <target>debian-x86_64</target>
  <target-version>12</target-version>
  <target-arch>x86_64</target-arch>

```

**ShipDriver-sd3.2.3-debian-A32-12.xml** 
```
  <target>debian-armhf</target>
  <target-version>12</target-version>
  <target-arch>armhf</target-arch>

```

**ShipDriver-sd3.2.3-debian-A64-12.xml**
```
  <target>debian-arm64</target>
  <target-version>12</target-version>
  <target-arch>arm64</target-arch>
```

**ShipDriver-sd3.2.3-flatpak-22.08.xml**
```
  <target>flatpak-x86_64</target>
  <target-version>22.08</target-version>
  <target-arch>x86_64</target-arch>

```

**ShipDriver-sd3.2.3-flatpak-A64-22.08.xml**
 ```
 <target>flatpak-aarch64</target>
  <target-version>22.08</target-version>
  <target-arch>aarch64</target-arch>

```

**Comment by rgleason** [comment]
I decided to add to circleci/config.yml  the following:
at the top
```
        - build-flatpak-aarch64-2208:
            <<: *std-filters

```
at Line 556  with some reorganization of existing builds

```
    build-flatpak-aarch64-2208:
        machine:
            image: ubuntu-2004:202101-01
        resource_class: arm.medium
        environment:
        - OCPN_TARGET:  flatpak-aarch64
        - FLATPAK_BRANCH: stable
        - CLOUDSMITH_PKG_EXT: gz
        - SDK_VER: 22.08
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run:
            command: bash ci/circleci-build-flatpak.sh
        - deploy-code
```

I changed the Climatology version to 1.5.5.3 and commited and pushed.
the "flatpak-aarch64-2208"   has successfully built.

Now how to get it tested?

**Comment by rgleason** [comment]
I have asked for testing in the Cruiser Forum's  Climatology thread
https://www.cruisersforum.com/forums/f134/climatology-102281.html

**Comment by bdbcat** [comment]
I will try to test today. 
Take me an hour or so, since I need to build a larger sdcard image for my rPI4.
Please stand by.

**Comment by bdbcat** [comment]
Climatology v1.5.5.3 for flatpak/aarch64 imports, loads, and runs just fine by live test.

Related note:  There really is no reason at all to build flatpak 20.08.  SDK 20.08 is long gone, unavailable.  O58 requires SDK 22.08.  So no reason to ask users to test it.

**Comment by rgleason** [comment]
Great thanks Dave.  Is there any reason to test the Debian 12 Bookworm, or should I just assume it works? Bram hasn't tested or advised yet.

**Comment by bdbcat** [comment]
I will try to get to debian 12 test tonight.

**Comment by rgleason** [comment]
Closing. Done. Thanks!

**Comment by rgleason** [comment]
Later 8/1/2023 fixed Jammy.
