### ISSUE TITLE
CI: Warning about upgrade to pip 20.3.4 (near future)

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#324]
Squiddio warning

https://app.circleci.com/pipelines/github/rgleason/squiddio_pi/401/workflows/92fe7ee3-b006-4745-9426-388f4077c4ed/jobs/2780

WARNING: You are using pip version 19.2.3, however version 20.3.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by rgleason** [comment]
[Remove python3.8 and leave as python3](https://github.com/rgleason/testplugin_pi/commit/3396d9b5d5501d771232142c492a52da2b164eb6)

Does leaving this as python3 solve the problem?

**Comment by jongough** [comment]
It seemed to have a problem with python3.8 being unavailable for android-armhf, so I tried deploying with an orb and that worked.

**Comment by rgleason** [comment]
Great. Thanks. Closing
