### ISSUE TITLE
Simplify and cleanup files

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#328]
[Try to simplify and clean up files #55 ](https://github.com/rgleason/watchdog_pi/issues/55)

Review **changes made in Watchdog** to achieve this goal:

1. See changes in  File-summary.txt  (Keeps Mingw files)
[File-summary-revised.txt](https://github.com/jongough/testplugin_pi/files/12505741/File-summary-revised.txt)

2. Improvements to move ODAPI and json validation into the libs folder by bdbcat.
Make careful note of the changes needed for moving extinclude and extsrc into Libs as a library
Refactor libs. cleanup https://github.com/rgleason/watchdog_pi/pull/56
https://github.com/rgleason/watchdog_pi/commit/ca853f920e0944323d494d9c1cb2a090ebaec20d

Dave wrote:

> PR posted.  I refactored, to move ODAPI and JSON validation to "libs".  The logic is this:  If a source or header file is not particular to the plugin (e.g.ODAPI), or if it is likely that some other plugin may want to use it (e.g.JSON validation), then it goes into the common libs directory.  Same with GL stuff as internal to PluginDC.

> We can make the same refactor on other plugins at any convenient time.  For now, the "libs" directory will be a normal part of the plugin source tree, for all plugins using this structure.

> Soon enough, I will consolidate and synchronize "libs" for the various plugins using it.  I will then make a PR to Alec's opencpn-libs repo.  After acceptance there, we can adapt wd and other plugins to pull in opencpn-libs as a submodule.  

> This has the huge advantage that common code is not duplicated, so much easier to maintain.  Virtually all of the platform dependencies will be confined to the opencpn-libs submodule.  No more noise about gl2.h, or texfont, or all the other annoyances we have been fighting.

> I think it is safe now to delete the "OLD" directory and contents.

The next step is to make these changes in github.com/rgleason/testplugin_pi

**Comment by rgleason** [comment]
Weather Routing next   v1.15.6.0 in the streamline branch.
https://github.com/rgleason/weather_routing_pi/tree/streamline  
https://cloudsmith.io/~opencpn/repos/weather-routing-alpha/packages/?q=1.15.6.0

**Comment by rgleason** [comment]
Done. Closing  Thank you Dave.

**Comment by jongough** [comment]
I notice that you removed 'cutil.cpp' and 'cutil.h', both of these are needed in ODraw for line clipping. Should these be in opencpn-libs?

**Comment by jongough** [comment]
I now have a working ODraw with opencpn-libs. However I still need to use the following cpp files
```
    ocpnsrc/bbox.cpp
    ocpnsrc/cutil.cpp
    ocpnsrc/geodesic.cpp
    ocpnsrc/georef.cpp
    ocpnsrc/Hyperlink.cpp
    ocpnsrc/SelectItem.cpp
```
and headers
```
    ocpninclude/AISTargetAlertDialog.h
    ocpninclude/AISTargetQueryDialog.h
    ocpninclude/bbox.h
    ocpninclude/cutil.h
    ocpninclude/geodesic.h
    ocpninclude/georef.h
    ocpninclude/Hyperlink.h
    ocpninclude/SelectItem.h
    ocpninclude/timers.h
```

I will now put this up to github and see how the builds go.

**Comment by rgleason** [comment]
Jon, I would send Dave an email with a link to this guestion as they are working on opencpn-libs now,  
abut ocpn_draw and opencpn-libs.  He responds usually in maybe 5-8 hrs.
