### ISSUE TITLE
Disable Appveyor Builds

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#331]
1. Put a tag in the push commit  (one temporary alternative)
2.  Disable the Plugin webhook in github account settings. 
3.  In github plugin project, pick Settings at top, Webhook on left, 
4.  Click Edit next to  appeveyor pull_request and push  
5.  Login with credentials.
6.  At the bottom uncheck "Active"
7.  Pick "Update Webhook"
8.  This can be reactivated any time.

**Comment by jongough** [comment]
Appveyor is needed for VS2017, as circleci can only useable for VS2019. So the build capablity is still needed for a little while yet.

**Comment by rgleason** [comment]
Appveyor fails in the recent TP configurations we've developed, because a header is missing (lots of work done by bdbcat plus my research), so we are going to accept that WinXT is no longer supported, but provide O5.6 plugins for Win7 and up.

**Comment by rgleason** [comment]
Closing, moved to Process
