### ISSUE TITLE
sublibs PR-merge Handoff

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#338]
As an example, see this Testplugin Pull Request https://github.com/jongough/testplugin_pi/pull/337

1. To make a PR to your repository we need a "sublibs" branch in your repository.
   - Please browse to your repository, using Testplugin as an example, https://github.com/jongough/testplugin_pi then click on "master" and enter "sublibs" in the field to create a new branch. Thank you. I can now make a PR to you.
2. Once you accept the PR and merge it with your sublibs branch you may wish to pull that branch down and compile locally. You will have to make a few changes.
   - Appveyor is missing a key header causing a failure now, so [Disable the github webhook](https://github.com/jongough/testplugin_pi/issues/331)
   - We are using a circleci build for msvc (wx312) with no WinXT support now.
   - You should change any api 116 plugins to use api 117, see the changes made to testplugin as an example.
   - You may have to [reload opencpn-libs on your local machine](https://github.com/jongough/testplugin_pi/issues/332)

```
   For your local builds, after doing:

    Delete opencpn-libs,and then issue:
   $ git submodule update --init opencpn-libs
   $ git submodule update --remote --merge opencpn-libs
    Commit and push the results.
    This command pulls in all the latest updates to the opencpn-libs module.
    This will fix all builds except flatpak.

This is exactly what the CI process does. It will bring in a fresh copy of opencpn-libs from github.
It does not change the git repo contents at all, since you already have the git reference to opencpn-libs.

You generally need to only do this once (for each plugin), unless opencpn-libs is changed by me or Alec.
We will let you know if that happens.

Remember: treat opencpn-libs as a read-only library. Do not edit. Do not commit contents.

Dave
```

More information  [TP Convert to 'opencpn-libs' submodule #332 ](https://github.com/jongough/testplugin_pi/issues/332)

**Comment by jongough** [comment]
I have just pulled your sublibs (1.0.259.0) into my testplugin_pi and built it locally under ubuntu and have pushed it to github and the circleci build has worked there, 20 builds, but the appveyor builds have failed. Is this what you expect?

**Comment by rgleason** [comment]
Yes, as I wrote before, appveyor is missing a critical header and is not failing. The header has to be provided by appveyor as part of the build.

See how to disable it. Best way.
https://github.com/jongough/testplugin_pi/issues/331

**Comment by rgleason** [comment]
Also, you have to delete any msvc (wx312) O56 build when the plugin is api118.

We need this statement somewhere
If api>117 then do not build msvc (wx312)

**Comment by jongough** [comment]
I was just checking that I had the outcomes that you expected. I think that you can now create pull requests against my testplugin_pi sublibs branch and they should all apply OK. I am still time poor as I am now trying to catch up with things, but hopefully in the next week or so I should be able to put more time towards it.

**Comment by rgleason** [comment]
Thanks Jon. Great that it worked on ocpn_draw.

**Comment by jongough** [comment]
Is the intention of the sublibs to have every lib that a plugin may need in here? FE2 allowed extra libs to be added within the plugin, is this no longer needed?

**Comment by rgleason** [comment]
Jon there are several that had private "libs" in the "libs" directory. That is ok.  Most pi just use opencpn-libs.  If you have a candidate that is usrd by multiple pi you could suggest it.

**Comment by rgleason** [comment]
Moved to Process and Examples.
