### ISSUE TITLE
Travis raspbian-armhf  does not build

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#34]

**Comment by rgleason** [comment]
This may have something to do with travis itself.   Have you moved over to .travis-ci.com yet?  You can opt in to moving over and in a short time all the plugins you have there will move over. 

I've also noticed that .travis-ci.com sometimes does not pick up that there is a new build and I have to mess around to get it to show.  I have not yet discovered what the real trigger to get it to show is.

**Comment by jongough** [comment]
It is building OK for me with testplugin_pi
https://travis-ci.org/github/jongough/testplugin_pi/builds/668989604
Sometimes it does stall and may need to be restarted if it is important. Most of the time it is just one of the jobs that seems to take too long, i.e. >10m and gets auto terminated.

**Comment by rgleason** [comment]
Ok, I've found that it needs a kick sometimes too. thanks.
