### ISSUE TITLE
Flatpak builds not working

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#346]
They fail and have to be rerun several times and now one of them is not building at all.
We've been having a lot of trouble with flatpak
    https://app.circleci.com/pipelines/github/rgleason/pypilot_pi/150/workflows/a8208c81-0cce-4b36-bd5f-10b5d40e516f/jobs/2365
    https://github.com/rgleason/pypilot_pi/tree/master
    https://app.circleci.com/pipelines/github/rgleason/pypilot_pi?branch=master
    https://app.circleci.com/pipelines/github/rgleason/pypilot_pi/150/workflows/a8208c81-0cce-4b36-bd5f-10b5d40e516f/jobs/2378

https://github.com/rgleason/watchdog_pi/commits/master
https://github.com/rgleason/testplugin_pi/tree/master
https://github.com/rgleason/raymarine_autopilot_pi/tree/master

>AI Generated
> 
>bash ci/circleci-build-flatpak.sh
> 
>The error message suggests that the user is using deprecated options in their commands. They should replace the --force-yes flag with --allow in order to resolve the issue.
> 
>Additionally, the error message indicates that there are problems with the signature verification of repositories. This could be due to missing public keys. The user should try to update the public keys by running the following commands:
> 
>     sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4EB27DB2A3B88B8B
>     sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 536F8F1DE80F6A35
> 
> Furthermore, the error message mentions that the "Target Packages" and "Target Translations" are configured multiple times in the /etc/apt/sources.list.d/google-chrome.list and /etc/apt/sources.list.d/google.list files. The user should check these files and remove any duplicates to avoid conflicts.
> 
>Finally, the command sudo add-apt-repository -y ppa:alexlarsson/flatpak is failing because the specified PPA does not exist. The user should verify the correct PPA name and try again.

**Comment by jongough** [comment]
I have just checked shipdriver_pi and it is using the same ppa. It may be worth asking the maintainer of OCPN flatpak what needs to be used instead.

**Comment by rgleason** [comment]
Thanks Jon. Dave said it has started building again.

**Comment by rgleason** [comment]
This script needs to be updated next big upgrade.
