### ISSUE TITLE
CI: wxWidgets  3.2.4 upgrade to match OpenCPN? (near future)

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#349]
https://github.com/OpenCPN/OpenCPN/pull/3457#event-10685786789

Not needed until Opencpn Version 3.10 but can be done now.

**Comment by rgleason** [comment]
Now wxWidgets 3.2.4
https://github.com/OpenCPN/OpenCPN/pull/3508/commits/7e799dd41d54506c40acb0ae09740cad231ef038

**Comment by jongough** [comment]
Why is this update happening. We are still trying to bed down the current version?

**Comment by rgleason** [comment]
It comes from TransmitterDan's work. He is often in advance, so don't worry about it right now. We will need to change this at some undetermined point however.

**Comment by rgleason** [comment]
Also note different results with different build calls

https://github.com/OpenCPN/OpenCPN/pull/3508#issuecomment-1825018489

**Comment by transmitterdan** [comment]
> Why is this update happening. We are still trying to bed down the current version?

This is only happening in the local build script. Nothing changed in CI process. Also, if you use the local build script (buildwin\winConfig.bat) you can locally edit the file and set the wxWidgets version to anything you like.

**Comment by rgleason** [comment]
Would changing wxWidgets from 3.2.2 to 3.2.4 for building O5.10 plugins, cause backward compatibility issues with O5.8.4?  Is so, perhaps we should stick with wxWidgets 3.2.2?

**Comment by jongough** [comment]
I don't know. It shouldn't, but unless someone can test the plugins on the affected platforms it is a risk. I try to keep on the oldest, known to work, versions to avoid these issues. When a plugin needs a newer capability, or a platform no-longer supports the version that is when I do the upgrades. 

Something changed in wxWidgets that impacted OD when going to opencpn-libs (it was not opencpn-libs that caused it) where dialogs started to go wrong inside wxWidgets and all the callback sort routines and associated code had to be changed. So, I am wary of upgrading for upgradings sake.

**Comment by rgleason** [comment]
I understand your point very well. 
I suppose that Plugins using wxWidgets 3.2.2 won't be affected in compatibility with OpenCPN using wxWidgets 3.2.4 now? 
..and will not affect our plugin operations?
If so, the next set of plugins will be compatible with both OpenCPN 5.8.4 and 5.10, I believe.
