### ISSUE TITLE
Jons updates to match Dave's changes is missing lines

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#358]
https://github.com/jongough/testplugin_pi/pull/357/commits/37c86d802e39fd703fc232e8061d21868b422523
Update FE2 template files 
Line 159 and 354

          xcode: "13.4"
        resource_class: macos.x86.medium.gen2

**Comment by rgleason** [comment]
How can we be sure all changes are made and the two repositories are not diverging?

**Comment by rgleason** [comment]
Also  cmake/pluginsetup.cmake  Jon's is very different

Line 104

```
#       set(PKG_TARGET "${PKG_BUILD_TARGET}")
        set(PKG_TARGET "darwin-wx315")
        set(PKG_TARGET "${PKG_BUILD_TARGET}")
    endif() 


```

**Comment by rgleason** [comment]
Those are some of my questions after a visual comparison between rgleason (bdbcat merged) and jongough (with Jon's changes).

Since this is all about the "template" upon which all other plugins work, is there a way to make sure we have this right and get both versions together, knowing that they are right?

For example, the two differences noted above.

Jon has made some changes and Dave has made some changes.

**Comment by rgleason** [comment]
Well it is too late. The two repositories have diverged.
https://github.com/rgleason/testplugin_pi/compare/master...jongough:testplugin_pi:master

Even the other way is problematical.
https://github.com/jongough/testplugin_pi/compare/master...rgleason:testplugin_pi:master

Is there too much too different to make sense of this now ?

**Comment by jongough** [comment]
https://github.com/jongough/testplugin_pi/issues/358#issuecomment-1785095973
I believed that as macos 11(xcode 12) would not build it was to be left and not built. I was also led to believe that we were not supposed to be specifying wx315 anymore. Hence that part of the build is commented out.
this version of macos will build but with xcode 13.

**Comment by jongough** [comment]
Unfortunately I was making changes to get builds to work with opencpn-libs as it changed and to respond to requests for the full build process on MSVC and this made merging the changes Dave made 'difficult'.

I have just done a rebase of your repository on mine and the changes were minor, they just looked more as there were commented out code in your repository that were removed in mine.  I have created a pull request on your repository called 'master_update' that gets both to the same level, i.e. 1.0.276.0.

**Comment by rgleason** [comment]
Use the resource. See
https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718/8

until 2024

Then for free opensource use
 https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718/6

**Comment by jongough** [comment]
I have no proof either way for macos. I cannot test if you can use a later build of an app on macos. I do know that people with macos seem to have major issues when the OS updates and they get left behind.

As for resource classes testplugin used the default so does not have to specify it. This simplifies the process as a rebuild is not needed when an old class gets removed. My reading of he doco says that we may have issues around June next year when intel hardware is nolonger supported. Not really sure what to do then.

**Comment by jongough** [comment]
As OD seems to push the bounds with OCPN I am finding issues with the new version of OCPN/opencpn-libs. OD basically works, well will do when a change is made to opencpn-libs, but the dialog boxes seem to be a bit of a mess. They display, but don't seem to work quite as expected, so will need investigation.

**Comment by rgleason** [comment]
OK: . "This simplifies the process as a rebuild is not needed when an old class gets removed. My reading of he doco says that we may have issues around June next year when intel hardware is no longer supported"
- So at that time we have to specify an M1 resource.  Your two MacOS are building so that's good. 
 
- Now we need to confirm that they work on MacOS.   That would be either Testplugin or Ocpn_Draw most recent versions.   I think Dave has a Mac available. I can possibly ask him, once we know I'll merge your rebase.

Sorry OD dialog boxes aren't working.  Hope they start to behave.

**Comment by rgleason** [comment]
@bdbcat @jongough   Note this post too https://github.com/OpenCPN/OpenCPN/issues/3485#issuecomment-1786207868

**Comment by bdbcat** [comment]
#3485 has nothing to do with testplugin_pi.
Not at all relevant.

**Comment by bdbcat** [comment]
OD dialog boxes:
These are not managed by opencpn-libs.  WX dialogs are managed by the plugin code itself.

**Comment by jongough** [comment]
I'm working my way through what is and isn't working. Testplugin seems to be able to communicate with OD through both the ODAPI (binary) and JSON(text) with jsonschema validation. The version of widgets 'may' be causing the issue, but....

**Comment by bdbcat** [comment]
Rick:
Please do not stress on the CCI deprecation of some MacOS build bot images.  Will not affect us until January.

We have more immediate concerns now, namely the "commonization" of the FE2 template files.
Jon, is testplugin ready, and would you like my input on the FE2 template files?
Or would you rather I wait until you stabilize TP, and then adopt your changes for all of Ricks managed plugins?

**Comment by rgleason** [comment]
I will butt out of this. Sorry.

**Comment by jongough** [comment]
As far as I know the two repositories should be aligned now. I have done a merge on both to get to the point where they are the same. They are now at 1.0.278.0 and include all the changes. 

The macos builds are not using specified resource classes as the default one is the one that was being specified. When the current one is deprecated a new one will be the default. As we are opensource and not paying for the service we cannot gain anything useful from specifying the default.

So both repositories can be used, but I would prefer if changes are submitted as pull requests to my repository when they are working. This 'should' eliminate discrepancies that appear to creep in.

Dave, what changes would you like to see to the FE2 template files? I think I have all of your changes incorporated fully now and a couple of mine to help build for MSVC IDE's the installable packages. Also, the current version could be used to build locally approximately half of the environments using circleci local, some of the others can be done via batch files in the native environments.

**Comment by rgleason** [comment]
Closing now. Thanks
