### ISSUE TITLE
CI: Update old android builds  (near future)

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#366]
https://github.com/OpenCPN/OpenCPN/pull/3539/commits/3d7d7443687fb118f1e547a4c3dd482af9af888f

**Comment by jongough** [comment]
Is there a particular problem this change is designed to fix? Testplugin already uses 'cimg' images and that can be updated, if needed to the 2023 from 2021 version.

**Comment by rgleason** [comment]
Yes, I suppose TP is ahead and using cimg, but perhaps the version should be updated at some point here.

**Comment by jongough** [comment]
I am trying not to chase the development tail and end up doing multiple rebuilds of all plugins because something changed. If there is a reason that the plugins need to be updated fine, but.....

**Comment by rgleason** [comment]
OK I will add future to each post....
I am not interested in chasing development tails either, but these things get popped up totally "after the fact" and cause tail chasing to catch up!!! 
I have had enough to that type of thing so this is my response, to try to keep an eye out for CI issues that we need to address at some time in the near future by following the developments in OpenCPN.

**Comment by rgleason** [comment]
[Try orb deployment for android-armhf](https://github.com/rgleason/testplugin_pi/commit/9746bc17188734188e31398928b63c2c6848a304)
https://github.com/jongough/testplugin_pi/commit/9746bc17188734188e31398928b63c2c6848a304
