### ISSUE TITLE
CI: MacO update maybe? (near future)

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#367]
https://github.com/OpenCPN/OpenCPN/pull/3537/commits/75d7aae1390f579a1075e2da19ecbbd3125d6e98

**Comment by jongough** [comment]
Not sure what this is designed to fix. Is there an outstanding issue on plugins that this is relevant to?

**Comment by rgleason** [comment]
Development of OpenCPN occurs and things change, MacOS builds are being updated and we often have to follow these changes for the plugins. That is as much as I know so far.

**Comment by jongough** [comment]
Development does. Is there an issue that this is in response too? I have not seen anything on OD being unavailable or not working (acknowledging that windows 4K screens seem to be a problem for plugins with icons which I have attempted a work around) since it became available in the master stream.

**Comment by rgleason** [comment]
Jon, These CI threads are really more about the future. Maybe I should add that to each of the threads.  They are a tickler to remind us of things that might need to be done in the next version.

**Comment by rgleason** [comment]
Dave, committed this, being tested.
https://github.com/jongough/testplugin_pi/commit/7d804fcf1901600317186752f967b14f8e8e1d87
