### ISSUE TITLE
circleci-build-trusty.sh

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#38]
https://github.com/rgleason/weather_routing_pi/commit/f0c15514c04c7c97302310c267abdefd628a96b7
To get trusty building for weather-routing I had to add

```
sudo apt-get install libglu1-mesa-dev   
# from weather_routing  branch:master ci/circleci-build-trusty.sh

```
after
```
sudo apt-get --allow-unauthenticated install -f
rm -f ./*all.deb
```

I am not sure if this is unique to weather-routing, so have not made a PR.

**Comment by jongough** [comment]
I think that library should be added to line 8 where 'deviscripts' is installed, i.e.
sudo apt-get install devscripts equivs gdebi libglu1-mesa-dev

I will add it that way to the testplugin_pi script.

**Comment by rgleason** [comment]
Jon point of information.
Does weather routing need code updates to   better use gtk3? 
What  parts need to be updated do you think?

**Comment by jongough** [comment]
If it builds OK with the gtk3 builder (all part of the stack), then no there is no need to change.

**Comment by rgleason** [comment]
Jon, I think trusty is using gtk2,  and we had to add  

sudo apt-get install libglu1-mesa-dev   

because we were getting an error.

So I am wondering if trusty every supports gtk3, and if so are there changes to weather_routing  src files that are needed  (because you mentioned that some of the code is very old)?

**Comment by rgleason** [comment]
Also I can't remember, but I don't think weather_routing does build with gtk3, that is why I have the question.
