### ISSUE TITLE
Fix pluginconfig.cmake for Apple due to some permissions issue?

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#384]
https://github.com/jongough/ocpn_draw_pi/pull/546/files/0b716fed3a4b336721dc000f0fd9546e011aa840..c6a9beea95caa47cb77595f70de8ea6e83857cab#diff-07607edf79eac47f34bb88cfde37a8af3216307a1b6912d3c3dc9ec4d58c5619

Is this change needed for all TP Plugins?

**Comment by jongough** [comment]
Just making minor updates to accommodate the changes made for ODraw into testplugin.

**Comment by rgleason** [comment]
Done
