### ISSUE TITLE
Check ADAPI messaging for boundaries - Watchdog

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#386]
Need to confirm that Weather_routing and WatchDog boundaries are working properly with Ocpn_draw.

**Comment by jongough** [comment]
The ODAPI is working, but there appears to be issues with watchdog. I am not sure it is using the correct alarm code for inclusion alarms, it seems to use the anchor alarm. I have not had time to check the other parts of it. However, it is making the calls to OD to get the information, but it is what it does with the returned information that seems a little strange.

**Comment by rgleason** [comment]
Thanks Jon, I thought something was amiss. I will test it more completely this weekend.  I'll also check weather_routing.
