### ISSUE TITLE
Fails to generate a textpoint

### ISSUE THREAD

**Issue by Rasbats** [jongough/testplugin_pi#393]
Used ODAPI to create a textpoint with TP (1.0.297).

This always creates a textpoint at position lat 0, lon0. Have I got the format for lat/lon wrong?

I have been creating a valid textpoint with a plugin I have been working on so I believe the problem is with TP.

**Comment by jongough** [comment]
When using TP to create the textpoint you need to tell it where you want the point. The create textpoint screen looks like:
![image](https://github.com/jongough/testplugin_pi/assets/2803240/61ba3328-d5e4-454e-9fae-2e7c3780ce18)
You can either fill in the Lat and Lon of where you want the point placed or just left mouse button click on the OCPN page and the Lat and Lon will be filled in with the pointer position. It will then look like this:
![image](https://github.com/jongough/testplugin_pi/assets/2803240/083ed69f-b380-4875-906f-e281d49b4fbb)

I have just done this on an Ubuntu system. If it does not work for you can you tell me what environment you are using?

**Comment by Rasbats** [comment]
Thanks Jon. Yes it works. Not sure what was going on yesterday. On Windows here.

**Comment by jongough** [comment]
Glad its working for you. I think it may not be overly intuitive if you haven't done it before or for a long while. Testplugin started as a way to test and build the ODAPI in both binary and json, it has since evolved to be the basis for the FE2 automated build process. So is continually updated, but mainly for build processing now.

**Comment by Rasbats** [comment]
I am working with AIS data for bridge clearances in the EU waterways (amongst other things). Your text points look ideal for displaying this data.
