### ISSUE TITLE
cmake files formatting

### ISSUE THREAD

**Issue by leamas** [jongough/testplugin_pi#4]
Having a uniform formatting enhances readability. The main CMakeLists.txt + some (not all) support files has been successfully reformatted using https://github.com/cheshirekow/cmake_format. The configuration file (almost pristine) is available as https://raw.githubusercontent.com/OpenCPN/OpenCPN/master/.cmake-format.yaml.

All in all this has created a much more consistent formatting of the CMake setup files. It might make sense to consider also for a template project

**Comment by jongough** [comment]
Done. Patch 1.0.33 contains the updates

**Comment by leamas** [comment]
Right... but I miss something. You are not updating master, so where is this 1.0.33?

**Comment by jongough** [comment]
Not yet uploaded as I am going through the other stuff you have raised.

**Comment by jongough** [comment]
I have pushed but not pulled 'cmake_flatpak' as a branch in which I am making the changed

**Comment by rgleason** [comment]
Shouldn't  this information also be a page in dev manual?

**Comment by jongough** [comment]
This is really a 'style' issue that Alec has. As long as a module is consistent within itself I don't really see the issue. It is preferable not to have unused variables, but sometimes it is necessary to receive the output from a module call, but you don't actually want to do anything with it.  So I go with whatever the developer wants to use, its not my task to 'correct' them to my point of view.

**Comment by rgleason** [comment]
Added this to  https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:developer_guide:code_formatting
