### ISSUE TITLE
Python Test - Typo problem

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#404]
https://github.com/jongough/testplugin_pi/pull/403/commits/fdca892442023e2220f83ab397d8fbb2631f8b3b

@jongough
[Try without updating python for macos](https://github.com/jongough/testplugin_pi/pull/403/commits/fdca892442023e2220f83ab397d8fbb2631f8b3b)
[fdca892](https://github.com/jongough/testplugin_pi/pull/403/commits/fdca892442023e2220f83ab397d8fbb2631f8b3b)

       - run: bash ci/circleci-build-macos.sh
        - deploy-code:
            deploy_use_orb: false
            install_pythob: false    <<--- Typo problem  Line 154
    build-macos-universal:
        macos:
            xcode: "14.2"

**Comment by jongough** [comment]
Thanks. Fixed in next version.
