### ISSUE TITLE
Use native apple  macos gl.h header?

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#405]
Jon,
I was searching for this PR from Leamas to reference it here, because it raises a question about our macos builds using the right gl.h header.

https://github.com/seandepagnier/weatherfax_pi/pull/152/commits/858a5df32bbfeaf82e2a7c09e41e876ee0f657fb

>  src: Use the native apple gl.h header.
> 
> The gl.h header is available in all MacOs versions. Since the opengl
> headers are designed to be adapted by the OS vendor, they actually do
> differ on different platforms. For this reason, using the version
> provided by the OS, here MacOS, should be preferred if available.
> 
> Adjust the include path on MacOS to the location where gl.h et. al.
> lives.

I don't know if it would apply to Testplugin macos builds.

**Comment by jongough** [comment]
FE2 uses opencpn-libs to provision this. It is provided by the CMakeLists.txt file in the plugin_dc directory, line 29. If it is wrong then that is an issue for opencpn-libs.

**Comment by rgleason** [comment]
Great. Thanks. I will close.
