### ISSUE TITLE
 Correct debian/12/x86_64 build at CircleCI

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#415]
Jon, look at this PR for weatherfax please

https://github.com/rgleason/weatherfax_pi/pull/175

On 12/20/2024 5:16 PM, Frederick Gleason wrote:
>
> We need to get this working. Thanks.
>
>   build-debian-x86_64-12-bookworm:
>         machine:
>             image: ubuntu-2204:current
>             resource_class: arm.medium   <-----????
>         environment:
>         - OCPN_TARGET: bookworm
>         - BUILD_GTK3: true
>         - WX_VER: 32
>         - DEPLOY_USE_ORB: true
>         - BUILD_ENV=debian
>         - DOCKER_IMAGE=debian:bookworm
>         steps:
>         - chec
>         - run: chmod a+x ci/*.sh
>         - run:
>             command: ci/circleci-build-ubuntu-docker.sh
>             no_output_timeout: 30m
>         - deploy-code
>
>
> Dave made  changes to weatherfax_pi so he could debug and correct weatherfax use of files and data.
>
>

**Comment by jongough** [comment]
For me this process already works. In the circleci job I get the following:
![image](https://github.com/user-attachments/assets/3fc61fbb-4ed2-491d-ac08-8b82cf8e67c9)
Which shows the correct resource_class as it is the current default.

**Comment by rgleason** [comment]
Jon made some changes here that seem to build.
https://github.com/jongough/ocpn_draw_pi/releases/tag/v1.8.57.0

https://github.com/jongough/testplugin_pi/pull/416

**Comment by rgleason** [comment]
https://github.com/jongough/testplugin_pi/commit/ead23ae31405048dfa3422db6da1793f11b65349

Fixed.
