### ISSUE TITLE
src: whitespace and formatting issues.

### ISSUE THREAD

**Issue by leamas** [jongough/testplugin_pi#5]
The current code is plagued with all sorts of basic encoding, whitespace and formatting issues. Some examples:

    [non-ascii files]
    > file $(git ls-files .) | grep -i unicode
    cmake/NSIS.template.in:               UTF-8 Unicode text, with very long lines, with CRLF line terminators
    ocpnsrc/TexFont.cpp:                  C source, UTF-8 Unicode text
 
    [ trailing whitespace]
    > grep -rl '[[:blank:]]$' $(git ls-files) | wc -l
    72

    [DOS line endings]
    > grep -l $'\r' $(git ls-files) | grep -v .png | grep -v .ico | grep -v .jpg
    cmake/NSIS.template.in
    cmake/version.h.in
    src/tpdc.cpp

A template should probably try to get these things right from the beginning. Providing git hooks to block such stuff from being merged also makes sense. 

The overall formatting is also messy enough to generate compilation warnings (!)  A template might consider to use for example clang-format (with a modified .cmake-format) to clean up the situation.

**Comment by leamas** [comment]
See also https://github.com/OpenCPN/OpenCPN/issues/1118#

**Comment by rgleason** [comment]
Has this been fixed in TestPlugin?  Can we close it?

**Comment by jongough** [comment]
You have missed the point of the plugin. It is a test plugin that I used to help build the ODAPI and test it out. It is also available for other developers to see how to interact with the ODAPI. It is not intended to be a clean, templated, plugin to be used as an example of how to write one. 

The only warnings I see within the code are for unreferenced local variables. Hardly surprising for a test plugin which is designed to be modified. I see no messages, in circleci, that suggests there is anything wrong with the code. I do see warnings about Windows XP, with is an OCPN issue.

NSIS.template.in is not my file but a copy of one taken from OCPN.

**Comment by rgleason** [comment]
Isnt it time to close this now?

**Comment by jongough** [comment]
I suppose. I did change my editor defaults to remove blanks at the end of the line and many of the modules Alec has changed have a similar issue. As for the other stuff, well it is a 'test' plugin designed to allow complex testing of interfaces, not to be a textbook example of how to write code.
