### ISSUE TITLE
gtk2 and gtk3 use

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#63]
https://github.com/OpenCPN/OpenCPN/issues/1898
Should the plugins have something for testing gtk3?

This is something I discovered in trying to test plugins configured for gtk3, do you think anyone would bother to explain what the parameters for use of gtk3 plugins should be?  No.

"I would be interested in any conclusions or summaries with regard to the use of
Opencpn with gtk3/without and plugins with gtk3/without.
Guidelines for install and use."

**Comment by jongough** [comment]
The builds are done for gtk2 & gtk3 and the plugin manager should pick the correct one. If you are building OCPN and/or the plugins locally then you would need to be careful which one you choose. Apart from that I don't think there should be an issue.

**Comment by rgleason** [comment]
Ok, so as I understand this,  

whether we have a gtk3 or gtk2 plugin, the plugin manager and Opencpn will support it.

**Comment by jongough** [comment]
At the moment we have to build for all environments and the Plugin Manger at run time will pick the correct version of the plugin for the OCPN environment. So if you use a gtk3 OCPN the gtk3 version of the plugin will be installed. I am not quite sure what will happen if you use the gtk2 version of everything and then update OCPN to use gtk3 but not the plugins. Perhaps someone with the correct test environments should try this to make sure it works, or fails gracefully.

**Comment by rgleason** [comment]
This gets pretty complicated doesn't it.

**Comment by jongough** [comment]
It does. I just wish more people would do serious testing and look at edge cases.
