### ISSUE TITLE
metadata.xml  Issues

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#74]
Jon, when I build locally, 
1 .the tarball is created but it does not have the metadata.xml file inside it.
2. I can rename the xml file and copy it into the tarball, but then import plugin does not work.
3. I think the reason it doesn't work is perhaps the xml file does not have the new ARCH field?
4. or I have the metadata.xml file in the wrong location in the tarball.
.

**Comment by rgleason** [comment]
I think one of the problems comes from windows not supporting some of the commands locally that join the metadata into the tarball.  

Even though I have bash available.
However the xml file still does not seem to be properly formed.

**Comment by rgleason** [comment]
Ah, this time I found the new line
<target-arch>x86_64</target-arch>
So that isn't the problem.

**Comment by rgleason** [comment]
When testplugin is built for windows, the xml file is not added to the tarball. 
I have renamed the xml to metadata.xml and added it to the tarball.
When import plugin is used on the file, it is successful, but when I choose to update testplugin it fails because it can't find the URL.

The tarball url in the xml file is
<tarball-url>
    https://dl.cloudsmith.io/public/--pkg_repo--/raw/names/--name--/versions/--version--/--filename--
  </tarball-url>

**Comment by rgleason** [comment]
This is a kind of side challenge, which can be resolved later.

**Comment by jongough** [comment]
I am looking into it, but it is the way that you need to run bash under windows to construct the file correctly and that is proving 'interesting' locally.

**Comment by jongough** [comment]
Don't forget that the cloudsmith-upload.sh does some processing to get it to work and does update the 'xml' that is produced with relevant information. It is not as simple as copy/paste.

**Comment by rgleason** [comment]
Jon, cloned your tesplugin repository and I find that this works:
From x86 Command Prompt VS2017:
-     cmake -T v141_xp ..
-     cmake --build . --target package --config release
-     The exe, tarball and xml are put in the build directory. The xml is not inside tarball.

From Git-Gui browse to testplugin_pi, open the git repository. 
-     Pick from Menu "Repository > Git Bash"
-     Enter "cd build"
-     Enter  "bash cloudsmith-upload.sh"
-     Then the metadata.xml is found in the tarball just above the testplugin_pi.... directory.

The metadata.xml file is this

```
<?xml version="1.0" encoding="UTF-8"?>
 <plugin version="1">
   <name> testplugin </name>
   <version> 1.0.100.0 </version>
   <release> 0 </release>
   <summary> Plugin to test examples of the ODAPI and JSON interface for ODRAW 1234# </summary
 >
 
   <api-version> 1.16 </api-version>
   <open-source> yes </open-source>
   <author> Jon Gough </author>
   <source> https://github.com/jongough/testplugin_pi.git </source>
 
   <description>
     testplugin Plugin is used to test out the ODraw API and demonstrate how to use it success
 fully from another plugin
   </description>
 
   <target>msvc</target>
   <target-version>10.0.18363</target-version>
   <target-arch>x86_64</target-arch>
   <tarball-url>
     https://dl.cloudsmith.io/public/--pkg_repo--/raw/names/--name--/versions/--version--/--fi
 lename--
   </tarball-url>
   <info-url> https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:plugin
 s:safety:odraw1.6_pi </info-url>
 </plugin>
```

Is this path correct? I am wondering how this all works.

<tarball-url>
     https://dl.cloudsmith.io/public/--pkg_repo--/raw/names/--name--/versions/--version--/--fi
 lename--
   </tarball-url>

**Comment by rgleason** [comment]
Also when I try  cmake -T v141_xp .. using the promptt
I get errors in my version

```
-- *** Staging to build testplugin_pi ***
-- CIRCLECI: , Env CIRCLECI:
-- TRAVIS: , Env TRAVIS:
fatal: No such remote 'origin
upstream'
CMake Error at cmake/PluginConfigure.cmake:52 (string):
  string sub-command FIND does not allow one to select REVERSE as the output
  variable.  Maybe you missed the actual output variable?
Call Stack (most recent call first):
  CMakeLists.txt:141 (INCLUDE)


CMake Error at cmake/PluginConfigure.cmake:55 (string):
  string sub-command LENGTH requires two arguments.
Call Stack (most recent call first):
  CMakeLists.txt:141 (INCLUDE)


-- START_URL: 11, STRING_LENGTH: 10
CMake Error at cmake/PluginConfigure.cmake:57 (string):
  string sub-command SUBSTRING requires four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:141 (INCLUDE)


-- GIT_REPOSITORY:
-- Git Branch: "master"
-- Git Tag: ""
```
etc and it goes down to naming the packages but does not complete preparations.

PluginConfigure.cmake  LINE 52

   string(FIND ${GIT_REPOSITORY_URL} ${GIT_REPOSITORY_SERVER} START_URL REVERSE)

**Comment by rgleason** [comment]
Jon's way to compile locally and make the tarball.

   Get the latest Weatherfax_pi (master), create a new directory, go into that and issue the requisite commands.
For Windows
Git Bash (Git-Gui):
Make sure you are in the correct, clean (empty) directory for a build
cmake -T v141_xp ..
cmake --build --target Package --config Release
./cloudsmith-upload.sh   
The cloudsmiiths script must be executed or the metadata will not be put into the tarball

For Linux:
Make sure you are in the correct, clean (empty) directory for a build
cmake -DWXWIDGETS_FORCE_VERSION=3.0 -DCMAKE_BUILD_TYPE=Release ..
make -j4
./cloudsmith-upload.sh

Under linux change the number of -j4 to how many processors you have, I use -j12 (6 real processors, 2 threads per processor AMD  Ryzen 5 1600). Under windows VS will pick the number of processor automatically.

**Comment by rgleason** [comment]
Jon, I am going to close this.
