### ISSUE TITLE
Deployment to Cloudsmith Manual-Pkg

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#9]
@Alec Leamas
Under Manual-PKG below, is the 
- testplugin-flatpak-18.08.gz v1.0.41.6 
an installer file?  I don't think so. Should it be there?

Under Manual-PKG below, aren't we missing an installer file for MacOS?

Have done a new version v1.0.41.6  Stable + Manual-Pkg Test, 
by git add CMakeLists.txt
and git commit -am "Version v1.0.41.6  Stable + Manual-Pkg"
then  git tag v1.0.41.6
and then pushed   git push --tag origin cmake_flatpak_test:cmake_flatpak_test
(built all files in under 6 min, except flatpak which completed in 6.5 min)
URL here:  https://github.com/rgleason/testplugin_pi/commits/cmake_flatpak_test
which pushes the files to 

**CS  STABLE**   10 files , 5 OS
https://cloudsmith.io/~rick-gleason/repos/opencpn-plugins-stable/packages/
- testplugin-flatpak-18.08.gz v1.0.41.6
- testplugin-flatpak-18.08-metada… v1.0.41.6 
- testplugin-msvc-10.0.14393-tarb… v1.0.41.6 
- testplugin-msvc-10.0.14393-meta… v1.0.41.6 
- testplugin-darwin-10.13.6.gz v1.0.41.6 
- testplugin-darwin-10.13.6-metad… v1.0.41.6 
- testplugin-ubuntu-16.04.gz v1.0.41.6 
- testplugin-ubuntu-16.04-metadata v1.0.41.6 
- testplugin-mingw-10.gz v1.0.41.6 
- testplugin-mingw-10-metadata v1.0.41.6

**CS Manual-PKG** 4 files
 https://cloudsmith.io/~rick-gleason/repos/opencpn-plugins-pkg/packages/
- testplugin-flatpak-18.08.gz v1.0.41.6    <---installer file?
- testplugin-msvc-10.0.14393-inst… v1.0.41.6 
- testplugin-ubuntu-16.04.deb v1.0.41.6 
- testplugin-mingw-10.exe v1.0.41.6
- testplugin-darwin-10.13.6.pkg v1.0.41.6   <--this also exists, found later.
- Don't we need a macOS installer file here?

**Comment by jongough** [comment]
If your circleci will do macos then it 'should' work. I cannot test as my circleci does not do macos currently, still waiting.

What does squiddio do when you run the same process? I thought I had it working the same way.

**Comment by rgleason** [comment]
Is "Darwin" macOS,  look under CS STABLE list above?  --Why call it that?  Why not MacOS?

So from this below, the file upload to  "rick-gleason/opencpn-plugins-pkg/"
to it should be a  xxxxpkg file  but this name does not look right.

https://app.circleci.com/jobs/github/rgleason/testplugin_pi/94
```
Checking raw package upload parameters ... -/OK
Checking Testplugin-Plugin_1.0.41-ov50-1.16.pkg file upload parameters ... |\-/|OK
Requesting file upload for Testplugin-Plugin_1.0.41-ov50-1.16.pkg ... \-/|OK
Uploading Testplugin-Plugin_1.0.41-ov50-1.16.pkg:  [####################################]  100%
Creating a new raw package ... \-/|\-OK
Created: rick-gleason/opencpn-plugins-pkg/testplugin-plugin_1041-ov50-116pkg-10 (JEXdludDKedz)
```

Ok, I just found out that it was uploading, for example,
"testplugin-darwin-10.13.6.pkg v1.0.41.5 "

but now for v1.0.41.6  it is not!!
See this ,  it built properly.
https://github.com/rgleason/testplugin_pi/runs/329378492
See this,  
https://cloudsmith.io/~rick-gleason/repos/opencpn-plugins-pkg/packages/

**Comment by rgleason** [comment]
Just found these two "Package Group" viewss which are very helpful
https://cloudsmith.io/~rick-gleason/repos/opencpn-plugins-stable/groups/
With this screen I found that I had not seen the "Darwin" or MacOS xml file to download it.
So the problem comes from my not seeing the Darwin xmll file and downloading it for inclusion in the ocpn-plugins.xml file

Also this "Package Group" view [left side menu at the top] for manual-pkg is good too.
https://cloudsmith.io/~rick-gleason/repos/opencpn-plugins-pkg/groups/
Which clearly shows that darwin was deployed to opencpn-plugins-pkg

**Comment by rgleason** [comment]
This is not a problem. It is ok. Will close this shortly.
